#+TITLE: dotemacs
#+AUTHOR: Tony Day
#+EMAIL: tonyday567 at gmail dot com
#+COLUMNS: %25ITEM %30tangle
#+PROPERTIES: tangle yes

* Upfront
:PROPERTIES:
:OPEN: [2012-08-01 Wed 18:27]
:LAST: TODO [2012-08-01 Wed 18:27]
:END:
#+begin_quote
  business in the front, party in the back

  -- [[http://en.wikipedia.org/wiki/The_Mullets_(TV_series)][The Mullets]]
#+end_quote

Emergency status hack-attack city.

- [X] take all the starter-kit guff and place it here
- [X] init.el should be placed here too
- [ ] clean up/triage 


* init.el

The init.el file is the only file in the startup of emacs
that *needs* to be a .el file.  If you update it here and don't
tangel it the old copy will remain in place only to be overwritten
automatically next restart.

Not much we can do about that.

It weighs in at a muscular 3 lines and does exactly 3 things.
1. finds out where it is. This means that it can start anywhere if
  pointed to with:
  
  #+begin_src sh :tangle no
    /Applications/Emacs.app/Contents/MacOS/Emacs -q -l not-the-home/init.el     
  #+end_src
  
  or

  #+begin_src sh :tangle no
    emacs -q -l not-the-home/init.el     
  #+end_src
  
  The other way to test outside of your regular ~/.emacs.d is to set
  $HOME=~/fakehome and place init.el in ~/fakehome/.emacs.d.  
2. loads the org directory (if it exists).  This is needed in case
  there is a more recent org-mode installed in which case usage of
  babel before loading the path will result in a mixed install.  Not
  fun debugging that.    
3. loads the /real/ init code, which i have called dotemacs and which
   is contained in this file.

#+begin_src emacs-lisp :tangle init.el
  ;; see org-init.org for documentation
  (setq working-dir
        (file-name-directory (or load-file-name (buffer-file-name))))
  (let ((org-dir (expand-file-name "src/org-mode/lisp" working-dir)))
    (add-to-list 'load-path org-dir))
  (org-babel-load-file (expand-file-name "dotemacs.org" working-dir))
#+end_src

* structure

Event and code order/structure.
- init.el loads
- dotemacs.org loads

There are some important sectioning that happens
- bootstrap. stuff that absolutely has to go at the front and load before
  everything else.
- guff. code that is not associated with packages but where ordering
  is unimportant.
- packages. packages loads that can be put most anywhere and can be
  put in alphabetical order.
- files. file loads that are files just for convenience (and can be loaded
  in alphabetical order).
- endboot. stuff that has to go at the end.

* bootstrap

** load-path
  :PROPERTIES:
  :tangle:   yes
  :END:
- [ ] work out reverse direction stuff
- [ ] necessity of overrides?
- [ ] intro to table->list technology
- [ ] wrap all dir technology
- [ ] protect default-directory

*** src subdirs

Borrowing from starter-kit, src is the place to dump your lisp code
and packages which dont come on down the elpa channel (~/.emacs.d/src)

I tend to keep git repos in ~/git and ln -s them to src.

  #+begin_src emacs-lisp
    (setq src-dir (expand-file-name "src" working-dir))
    ;; add the src directory to the load path
    (add-to-list 'load-path src-dir working-dir)
    ;; load all subdirectories
      (when (file-exists-p src-dir)
        (let ((default-directory src-dir))
          (normal-top-level-add-subdirs-to-load-path)))
  #+end_src


*** specific directories
- Load path etc.
  #+begin_src emacs-lisp
    (add-to-list 'load-path working-dir)
    (setq autoload-file (concat working-dir "loaddefs.el"))
    (setq package-user-dir (concat working-dir "elpa"))
    (setq custom-file (concat working-dir "custom.el"))
  #+end_src



** ubiquitous and core requires

Ubiquitous Packages which should be loaded on startup rather than
  autoloaded on demand since they are likely to be used in every
  session.
  #+begin_src emacs-lisp
    (require 'cl)
    (require 'saveplace)
    (require 'ffap)
    (require 'uniquify)
    (require 'ansi-color)
    (require 'recentf)
  #+end_src

** elpa

- Initialise ELPA archive repositories
  #+begin_src emacs-lisp
    (setq package-archives
          '(("original"    . "http://tromey.com/elpa/")
            ("gnu"         . "http://elpa.gnu.org/packages/")
            ("marmalade"   . "http://marmalade-repo.org/packages/")))
    (package-initialize)
   #+end_src
  

** package installs

- [ ] make essential orgtable

  (dolist (package '(magit))
    (unless (package-installed-p package)
      (package-install package)))

#+TBLNAME: table-packages
| package   | essential |
|-----------+-----------|
| magit     | yes       |
| yasnippet | yes       |
|           |           |



#+begin_src emacs-lisp      
    (defvar essential-packages
      (list 'yasnippet-bundle)
      "Libraries that are essential and should always be installed.")
    
    (unless package-archive-contents
      (package-refresh-contents))
    (dolist (package essential-packages)
      (unless (package-installed-p package)
        (package-install package)))
#+end_src

** Work around a bug on OS X where system-name is FQDN.
  #+begin_src emacs-lisp
    (if (eq system-type 'darwin)
        (setq system-name (car (split-string system-name "\\."))))
  #+end_src


** ubiquotous and loved settings
 #+begin_src emacs-lisp
   (whitespace-mode t)  
   (setq save-place t)
   (auto-fill-mode t)
   (column-number-mode t)
 #+end_src

** loved functions

*** starter-kit-pretty-lambdas
#+begin_src emacs-lisp
(defun starter-kit-pretty-lambdas ()
  (font-lock-add-keywords
   nil `(("(\\(lambda\\>\\)"
          (0 (progn (compose-region (match-beginning 1) (match-end 1)
                                    ,(make-char 'greek-iso8859-7 107))
                    nil))))))
(starter-kit-pretty-lambdas)
#+end_src


* guff
*** Window systems
#+srcname: starter-kit-window-view-stuff
#+begin_src emacs-lisp 
(when window-system
  (setq frame-title-format '(buffer-file-name "%f" ("%b")))
  (blink-cursor-mode -1))

(mouse-wheel-mode t)
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(prefer-coding-system 'utf-8)

(setq visible-bell t
      echo-keystrokes 0.1
      font-lock-maximum-decoration t
      inhibit-startup-message t
      transient-mark-mode t
      color-theme-is-global t
      delete-by-moving-to-trash t
      shift-select-mode nil
      truncate-partial-width-windows nil
      uniquify-buffer-name-style 'forward
      whitespace-style '(trailing lines space-before-tab
                                  indentation space-after-tab)
      whitespace-line-column 100
      ediff-window-setup-function 'ediff-setup-windows-plain
      oddmuse-directory (concat working-dir "oddmuse")
      xterm-mouse-mode t
      save-place-file (concat working-dir "places"))
#+end_src

*** Transparently open compressed files
#+begin_src emacs-lisp
(auto-compression-mode t)
#+end_src

*** Save a list of recent files visited.
#+begin_src emacs-lisp 
(recentf-mode 1)
#+end_src emacs-lisp

*** Highlight matching parentheses when the point is on them.
#+srcname: starter-kit-match-parens
#+begin_src emacs-lisp 
(show-paren-mode 1)
#+end_src

*** Other, spell checking, tabs, imenu and a coding hook
#+begin_src emacs-lisp 
  (set-default 'indent-tabs-mode nil)
  (set-default 'indicate-empty-lines t)
  (set-default 'imenu-auto-rescan t)
  (add-hook 'text-mode-hook 'turn-on-auto-fill)
  ;;(add-hook 'text-mode-hook 'turn-on-flyspell)  
  (defalias 'yes-or-no-p 'y-or-n-p)
  ;; Seed the random-number generator
  (random t)
#+end_src

**** possible issues/resolutions with flyspell
Most of the solution came from [[http://www.emacswiki.org/emacs/FlySpell][EmacsWiki-FlySpell]].  Here is one
possible fix.

***** Emacs set path to aspell
it's possible aspell isn't in your path
#+begin_src emacs-lisp :tangle no
   (setq exec-path (append exec-path '("/opt/local/bin")))
#+end_src

***** Emacs specify spelling program
- This didn't work at first, possibly because cocoAspell was
  building its dictionary.  Now it seems to work fine.
#+begin_src emacs-lisp :tangle no
  (setq ispell-program-name "aspell"
        ispell-dictionary "english"
        ispell-dictionary-alist
        (let ((default '("[A-Za-z]" "[^A-Za-z]" "[']" nil
                         ("-B" "-d" "english" "--dict-dir"
                          "/Library/Application Support/cocoAspell/aspell6-en-6.0-0")
                         nil iso-8859-1)))
          `((nil ,@default)
            ("english" ,@default))))
#+end_src

*** Hippie expand: at times perhaps too hip
#+begin_src emacs-lisp
(delete 'try-expand-line hippie-expand-try-functions-list)
(delete 'try-expand-list hippie-expand-try-functions-list)
#+end_src

*** Don't clutter up directories with files~
Rather than saving backup files scattered all over the file system,
let them live in the =backups/= directory inside of the starter kit.
#+begin_src emacs-lisp
(setq backup-directory-alist `(("." . ,(expand-file-name
                                        (concat working-dir "backups")))))
#+end_src

*** Default to unified diffs
#+begin_src emacs-lisp
(setq diff-switches "-u")
#+end_src

*** Cosmetics

#+begin_src emacs-lisp
(eval-after-load 'diff-mode
  '(progn
     (set-face-foreground 'diff-added "green4")
     (set-face-foreground 'diff-removed "red3")))

(eval-after-load 'magit
  '(progn
     (set-face-foreground 'magit-diff-add "green3")
     (set-face-foreground 'magit-diff-del "red3")))
#+end_src



* packages
** yasnippet
[[http://code.google.com/p/yasnippet/][yasnippet]] is yet another snippet expansion system for Emacs.  It is
  inspired by TextMate's templating syntax.
  - watch the [[http://www.youtube.com/watch?v=vOj7btx3ATg][video on YouTube]]
  - see the [[http://yasnippet.googlecode.com/svn/trunk/doc/index.html][intro and tutorial]]

*** load the yasnippet bundle
  #+begin_src emacs-lisp
    (require 'yasnippet)
    (yas/initialize)
  #+end_src

*** load the snippets defined in the =./snippets/= directory
  #+begin_src emacs-lisp
    (yas/load-directory (expand-file-name "snippets" working-dir))
  #+end_src

*** org yas play nicely

  The latest version of yasnippets doesn't play well with Org-mode, the
  following function allows these two to play nicely together.
  #+begin_src emacs-lisp
    (defun yas/org-very-safe-expand ()
      (let ((yas/fallback-behavior 'return-nil)) (yas/expand)))
    
    (defun yas/org-setup ()
      ;; yasnippet (using the new org-cycle hooks)
      (make-variable-buffer-local 'yas/trigger-key)
      (setq yas/trigger-key [tab])
      (add-to-list 'org-tab-first-hook 'yas/org-very-safe-expand)
      (define-key yas/keymap [tab] 'yas/next-field))
    
    (add-hook 'org-mode-hook #'yas/org-setup)
  #+end_src

** ido
*** ido mode
ido-mode is like magic pixie dust!
#+srcname: starter-kit-loves-ido-mode
#+begin_src emacs-lisp 
(when (> emacs-major-version 21)
  (ido-mode t)
  (setq ido-enable-prefix nil
        ido-enable-flex-matching t
        ido-create-new-buffer 'always
        ido-use-filename-at-point t
        ido-max-prospects 10))
#+end_src

*** recent-ido-find-file
#+begin_src emacs-lisp 
  (defun recentf-ido-find-file () 
    "Find a recent file using Ido." 
    (interactive) 
    (let* ((file-assoc-list 
            (mapcar (lambda (x) 
                      (cons (file-name-nondirectory x) 
                            x)) 
                    recentf-list)) 
           (filename-list 
            (remove-duplicates (mapcar #'car file-assoc-list) 
                               :test #'string=)) 
           (filename (ido-completing-read "Choose recent file: " 
                                          filename-list 
                                          nil 
                                          t))) 
      (when filename 
        (find-file (cdr (assoc filename 
                               file-assoc-list)))))) 
 #+end_src 




* files


* endboot

** custom file
#+begin_src emacs-lisp
  (load "custom.el" 'noerror)
#+end_src








** Starter Kit Bindings

Key Bindings.

*** You know, like Readline.
#+begin_src emacs-lisp 
(global-set-key (kbd "C-M-h") 'backward-kill-word)
#+end_src

*** Align your code in a pretty way.
#+begin_src emacs-lisp 
(global-set-key (kbd "C-x \\") 'align-regexp)
#+end_src

*** Completion that uses many different methods to find options.
#+begin_src emacs-lisp 
(global-set-key (kbd "M-/") 'hippie-expand)
#+end_src

*** Turn on the menu bar for exploring new modes
#+begin_src emacs-lisp 
(global-set-key [f1] 'menu-bar-mode)
#+end_src

*** Font size
#+begin_src emacs-lisp 
(define-key global-map (kbd "C-+") 'text-scale-increase)
(define-key global-map (kbd "C--") 'text-scale-decrease)
#+end_src

*** Use regex searches by default.
#+begin_src emacs-lisp 
(global-set-key (kbd "C-s") 'isearch-forward-regexp)
(global-set-key (kbd "\C-r") 'isearch-backward-regexp)
(global-set-key (kbd "C-M-s") 'isearch-forward)
(global-set-key (kbd "C-M-r") 'isearch-backward)
#+end_src

*** File finding
#+begin_src emacs-lisp 
  (global-set-key (kbd "C-x M-f") 'ido-find-file-other-window)
  (global-set-key (kbd "C-x C-p") 'find-file-at-point)
  (global-set-key (kbd "C-c y") 'bury-buffer)
  (global-set-key (kbd "C-c r") 'revert-buffer)
  (global-set-key (kbd "M-`") 'file-cache-minibuffer-complete)
  (global-set-key (kbd "C-x C-b") 'ibuffer)
  (global-set-key (kbd "C-x f") 'recentf-ido-find-file)  
#+end_src

*** Window switching. (C-x o goes to the next window)
#+begin_src emacs-lisp 
;;(windmove-default-keybindings) ;; Shift+direction
(global-set-key (kbd "C-x O") (lambda () (interactive) (other-window -1))) ;; back one
(global-set-key (kbd "C-x C-o") (lambda () (interactive) (other-window 2))) ;; forward two
#+end_src

*** Indentation help
#+begin_src emacs-lisp 
(global-set-key (kbd "C-x ^") 'join-line)
#+end_src

*** If you want to be able to M-x without meta
#+begin_src emacs-lisp 
(global-set-key (kbd "C-x C-m") 'execute-extended-command)
#+end_src

*** Help should search more than just commands
#+begin_src emacs-lisp 
  (global-set-key (kbd "C-h a") 'apropos)
#+end_src

*** Activate occur easily inside isearch
#+begin_src emacs-lisp 
  (define-key isearch-mode-map (kbd "C-o")
    (lambda () (interactive)
      (let ((case-fold-search isearch-case-fold-search))
        (occur (if isearch-regexp
                   isearch-string
                 (regexp-quote isearch-string))))))
#+end_src

*** Org-mode
Two global binding for Org-mode (see [[file:starter-kit-org.org][starter-kit-org]])

The [[http://orgmode.org/manual/Agenda-Views.html#Agenda-Views][Org-mode agenda]] is good to have close at hand
#+begin_src emacs-lisp
  (define-key global-map "\C-ca" 'org-agenda)
#+end_src

Org-mode supports [[http://orgmode.org/manual/Hyperlinks.html#Hyperlinks][links]], this command allows you to store links
globally for later insertion into an Org-mode buffer.  See
[[http://orgmode.org/manual/Handling-links.html#Handling-links][Handling-links]] in the Org-mode manual.
#+begin_src emacs-lisp
  (define-key global-map "\C-cl" 'org-store-link)
#+end_src

*** Rgrep
Rgrep is infinitely useful in multi-file projects.

(see [[elisp:(describe-function 'rgrep)]])

#+begin_src emacs-lisp
  (define-key global-map "\C-x\C-r" 'rgrep)
#+end_src


** Starter Kit Registers
Registers allow you to jump to a file or other location quickly. Use
=C-x r j= followed by the letter of the register (i for =init.el=, r
for this file) to jump to it.

You should add registers here for the files you edit most often.

#+name: starter-kit-registers
#+begin_src emacs-lisp :results silent
  (dolist
      (r `((?i (file . ,(concat working-dir "init.el")))
           (?I (file . ,(let* ((user user-login-name)
                               (org (expand-file-name (concat user ".org") working-dir))
                               (el  (expand-file-name (concat user ".el") working-dir))
                               (dir (expand-file-name user working-dir)))
                          (cond
                           ((file-exists-p org) org)
                           ((file-exists-p el)  el)
                           (t dir)))))
           (?s (file . ,(concat working-dir "starter-kit.org")))
           (?r (file . ,(concat working-dir "starter-kit-registers.org")))))
    (set-register (car r) (cadr r)))
#+end_src








* Starting guff
:PROPERTIES:
:tangle:   yes
:END:

** Load path
:PROPERTIES:
:OPEN:     [2012-10-11 Thu 13:19]
:LAST:     [2012-10-11 Thu 13:19]
:CLOSE:    [2012-10-11 Thu 13:19]
:END:

** Starter Kit Modifications

The orginal starter kit files have been modified in several areas:

- shift-select-mode turned on (my brain is hardwired like
  that) and a add few other personal tweaks
- I am trying out hunspell as a replacement for Aspell
- added some lisp dependencies
  - clojure-mode
  - slime (?)
- modified ido (not sure whether this was actually necessary)
- added this file to registers
- added to bindings

** Installs

- Package Installs

Just because I can, I list out all the packages I currently like
having (or resent having to have).

- Being split into relevant file deps
| package              | note                            |
|----------------------+---------------------------------|
| auctex               | defer                           |
| clojure-mode         | add to sk lisp                  |
| elisp-slime-nav      | add to sklisp                   |
| find-file-in-project | delay                           |
| idle-highlight-...   | incomplete                      |
| ido-ubiquitous       | package add elsewhere           |
| js-comint            |                                 |
| js2-mode             |                                 |
| json                 |                                 |
| magit                | added already                   |
| magithub             | learn                           |
| org                  | override from org-mode.org site |
| org-magit            |                                 |
| org2blog             |                                 |
| paredit              | package add                     |
| slime                | check                           |
| smex                 |                                 |
| xml-rpc              | dep for org2blog                |
| yaml-mode            | check                           |
| yasnippet-bundle     | sk added already                |
| zenburn-theme        | check how themes are added      |
|                      |                                 |


#+begin_src emacs-lisp  :tangle no
  (defvar starter-kit-packages-extra
        '(clojure-mode 
                elisp-slime-nav
                js-comint
                js2-mode
                json
                magithub
                org-magit
                org2blog
                paredit
                slime
                smex
                xml-rpc
                yaml-mode
                zenburn-theme)
        "Libraries that should be installed beyond the defaults.")
#+end_src

#+RESULTS:
: starter-kit-packages-extra



#+begin_src emacs-lisp
(unless package-archive-contents
  (package-refresh-contents))
(dolist (package '(clojure-mode 
                   elisp-slime-nav
                   js-comint
                   js2-mode
                   json
                   magithub
                   org-magit
                   org2blog
                   paredit
                   slime
                   smex
                   xml-rpc
                   yaml-mode
                   zenburn-theme))
  (unless (package-installed-p package)
    (package-install package)))
#+end_src

- Starter Kit Loads
  #+begin_src emacs-lisp
    (org-babel-load-file (expand-file-name "starter-kit-eshell.org" working-dir))
    (org-babel-load-file (expand-file-name "starter-kit-lisp.org" working-dir))
    (org-babel-load-file (expand-file-name "starter-kit-misc-recommended.org" working-dir))
  #+end_src

- Theme Loads
  - [ ] not sure how custom path gets modified

  #+begin_src emacs-lisp
    ;;(add-to-list 'custom-theme-load-path
    ;;           (concat package-user-dir
    ;;           '"/github-theme-0.0.3/"))
    (load-theme 'zenburn t)
    ;(load-theme 'github t)
  #+end_src

  

* personal loads
  :PROPERTIES:
  :tangle:   yes
  :END:
** Org                                                                 :org:
:LOGBOOK:
- State "TODO"       from ""           [2012-07-19 Thu 09:49]
:END:
:PROPERTIES:
		:ID:       29d70d42-d144-4fe0-b28b-0edfa6cf91cc
                :OPEN:     [2012-07-21 Sat 20:51]
:LAST: TODO [2012-07-23 Mon 11:27]
		:END:

*** Standard Settings
I start with Org mode
#+begin_src emacs-lisp 
  (add-to-list 'auto-mode-alist '("\\.\\(org\\|org_archive\\|txt\\)$" . org-mode))
  (add-hook 'org-mode-hook 'auto-fill-mode)
  (setq initial-major-mode (quote org-mode))
#+end_src

#+results:
: org-mode

*** Miscellaneous Settings
#+begin_src emacs-lisp 
  ;; shift-select
  (setq org-support-shift-select t)
  ;; keeps links so we can reuse/paste them again
  (setq org-keep-stored-link-after-insertion t)
  
#+end_src

#+results:
: t

*** Starter Kit Keybindings
   :PROPERTIES:
   :CUSTOM_ID: keybindings
   :END:
- global key bindings are in my [[file:starter-kit-bindings.org][starter kit bindings]]
- [ ] toggle iimage not worging
#+begin_src emacs-lisp
  (add-hook 'org-mode-hook
            (lambda ()
              (local-set-key "\M-\C-n" 'outline-next-visible-heading)
              (local-set-key "\M-\C-p" 'outline-previous-visible-heading)
              (local-set-key "\M-\C-u" 'outline-up-heading)
              ;; table
              (local-set-key "\M-\C-w" 'org-table-copy-region)
              (local-set-key "\M-\C-y" 'org-table-paste-rectangle)
              (local-set-key "\M-\C-l" 'org-table-sort-lines)
              ;; display images
              (local-set-key "\M-I" 'org-toggle-iimage-in-org)))
#+end_src

#+results:
| #[nil \300\301\302\303\304$\207 [add-hook before-save-hook org-encrypt-entries nil t] 5] | #[nil \300\301\302\303\304$\207 [org-add-hook change-major-mode-hook org-show-block-all append local] 5] | (lambda nil (local-set-key \216 (quote outline-next-visible-heading)) (local-set-key \220 (quote outline-previous-visible-heading)) (local-set-key \225 (quote outline-up-heading)) (local-set-key \227 (quote org-table-copy-region)) (local-set-key \231 (quote org-table-paste-rectangle)) (local-set-key \214 (quote org-table-sort-lines)) (local-set-key \311 (quote org-toggle-iimage-in-org))) | auto-fill-mode | #[nil \300\301\302\303\304$\207 [org-add-hook change-major-mode-hook org-babel-show-result-all append local] 5] | org-babel-result-hide-spec | org-babel-hide-all-hashes |

*** remaining key bindings
:PROPERTIES:
			:ID:       c0914200-d73d-4205-aba1-6cca8b2dd8f1
			:Effort:   0:15
                        :OPEN:     [2012-07-23 Mon 12:22]
:LAST:     [2012-10-11 Thu 13:11]
:CLOSE:    [2012-10-11 Thu 13:11]
			:END:

- [ ] still to rip and test
- [ ] switch to locally set???
#+begin_src emacs-lisp 
(global-set-key (kbd "<f5>") 'bh/org-todo)
(global-set-key (kbd "<S-f5>") 'bh/widen)
(global-set-key (kbd "<f7>") 'bh/set-truncate-lines)
(global-set-key (kbd "<f9> c") 'org-cycle-agenda-files)
(global-set-key (kbd "<f9> <f9>") 'bh/show-org-agenda)
(global-set-key (kbd "<f9> h") 'bh/hide-other)
(global-set-key (kbd "<f9> n") 'org-narrow-to-subtree)
(global-set-key (kbd "<f9> w") 'widen)
(global-set-key (kbd "<f9> u") 'bh/narrow-up-one-level)
(global-set-key (kbd "<f9> t") 'bh/insert-inactive-timestamp)
(global-set-key (kbd "<f9> v") 'visible-mode)
(global-set-key (kbd "<f9> p") 'org-publish-current-project)
(global-set-key (kbd "<f9> l") 'org-insert-last-link)
(global-set-key (kbd "M-<f9>") 'org-toggle-inline-images)
(global-set-key (kbd "C-x n r") 'narrow-to-region)
(global-set-key (kbd "C-c s") 'org-insert-subheading)
#+end_src

#+results:
: org-insert-subheading

*** search
 #+begin_src emacs-lisp  
(setq org-link-abbrev-alist
       '(("bugzilla"  . "http://10.1.2.9/bugzilla/show_bug.cgi?id=")
         ("url-to-ja" . "http://translate.google.fr/translate?sl=en&tl=ja&u=%h")
         ("google"    . "http://www.google.com/search?q=")
         ("gmap"      . "http://maps.google.com/maps?q=%s")
         ("omap"      . "http://nominatim.openstreetmap.org/search?q=%s&polygon=1")
         ("ads"       .
         "http://adsabs.harvard.edu/cgi-bin/nph-abs_connect?author=%s&db_key=AST")))
#+end_src

 #+results:
 | (bugzilla . http://10.1.2.9/bugzilla/show_bug.cgi?id=) | (url-to-ja . http://translate.google.fr/translate?sl=en&tl=ja&u=%h) | (google . http://www.google.com/search?q=) | (gmap . http://maps.google.com/maps?q=%s) | (omap . http://nominatim.openstreetmap.org/search?q=%s&polygon=1) | (ads . http://adsabs.harvard.edu/cgi-bin/nph-abs_connect?author=%s&db_key=AST) |

[[google:goofy]]

*** Encryption within Org
#+begin_src emacs-lisp 
(require 'org-crypt)
; Encrypt all entries before saving
(org-crypt-use-before-save-magic)
(setq org-tags-exclude-from-inheritance (quote ("crypt")))
; GPG key to use for encryption
(setq org-crypt-key nil)
(setq org-crypt-disable-auto-save nil)
#+end_src

#+results:



*** MobileOrg
:PROPERTIES:
:OPEN: [2012-07-23 Mon 11:48]
:LAST:     [2012-09-16 Sun 09:11]
:CLOSE:    [2012-09-16 Sun 09:11]
:END:

MobileOrg via Dropbox
#+begin_src emacs-lisp 
  (setq org-default-notes-file "~/stuff/org/refile.org")
  ;; Set to the name of the file where new notes will be stored
  (setq org-mobile-inbox-for-pull "~/stuff/org/refile.org")
  ;; Set to <your Dropbox root directory>/MobileOrg.
  (setq org-mobile-directory "~/Dropbox/MobileOrg")
#+end_src

#+results:
: ~/Dropbox/MobileOrg


Character encoding
- [ ] I think the character coding is already set ok by starter kit (but need to check)
#+begin_src emacs-lisp :tangle no
(if (eq system-type 'darwin)
    (progn
      (prefer-coding-system 'utf-8-unix)
      (set-default-coding-systems 'utf-8-unix)
      (if (< emacs-major-version 23)
          (set-keyboard-coding-system 'utf-8))
      (set-clipboard-coding-system 'utf-8)
      (set-terminal-coding-system 'utf-8)))
(if (or (eq system-type 'gnu/linux)
        (eq system-type 'windows-nt))
    (progn
      (prefer-coding-system 'utf-8-unix)
      (load-library "iso-transl")))
(define-coding-system-alias 'utf-8-emacs 'utf-8) ; needed by bbdb...
#+end_src

#+results:

*** Clocking into drawers
#+begin_src emacs-lisp 
;; Separate drawers for clocking and logs
(setq org-drawers (quote ("PROPERTIES" "LOGBOOK")))
;; Save clock data and state changes and notes in the LOGBOOK drawer
(setq org-clock-into-drawer t)
#+end_src

#+results:
: t


*** State and Change
:PROPERTIES:
:OPEN: [2012-07-23 Mon 19:44]
:LAST:  [2012-07-23 Mon 20:24]
:CLOSE: [2012-07-23 Mon 20:24]
:END:
- I use a customised state change hook to record when state changes occur.
#+begin_src emacs-lisp 
(setq org-log-done nil)
(setq org-log-into-drawer t)
(setq org-todo-keywords
      (quote ((sequence "TODO(t)" "NEXT(n)" "|" "DONE(d)"))))
(setq org-use-fast-todo-selection t)
(setq org-treat-S-cursor-todo-selection-as-state-change t)
(setq org-todo-state-tags-triggers nil)
;;(add-hook 'org-after-todo-state-change-hook 'zyg/log-state-change)
#+end_src

#+results:
| org-clock-out-if-current | org-checklist | zyg/log-state-change |

- It's frustrating, but org is usually correct
#+begin_src emacs-lisp 
(setq org-enforce-todo-dependencies t)
#+end_src

#+results:
: t

  
*** Plain Lists


- Demotion
  #+begin_src emacs-lisp 
  (setq org-list-demote-modify-bullet (quote (("+" . "-")
                                              ("*" . "-")
                                              ("1." . "-")
                                              ("1)" . "-"))))
  #+end_src

  #+results:
  | (+ . -) | (* . -) | (1. . -) | (1) . -) |

- Reset Repeater Checklist
  Repeater checklists saved my career.
  http://orgmode.org/worg/org-contrib/org-checklist.html
  #+begin_src emacs-lisp 
  (require 'org-checklist)
  #+end_src

  #+results:
  : org-checklist

- Use cycle for plain lists
  #+begin_src emacs-lisp 
  (setq org-cycle-include-plain-lists t)
  #+end_src

  #+results:
  : t



*** Priority

Using priorities kills the ability to ever use S-down to select
regions.  Can't bring myself to do it - instead I use an urgent tag.

#+begin_src emacs-lisp 
  (setq org-enable-priority-commands nil)
#+end_src

#+results:


*** Capture
:LOGBOOK:
CLOCK: [2012-08-23 Thu 20:49]--[2012-08-24 Fri 10:02] => 13:13
- Note taken on [2012-07-21 Sat 21:09] \\
  edited to account for timestamp stuff
:END:
:PROPERTIES:
:ID:       e79ecad1-2428-452a-b9d6-9fdd3ef8a174
:END:



#+begin_src emacs-lisp 
  
  (setq org-capture-templates
        (quote (("t" "todo (with link)" entry (file "~/stuff/org/refile.org")
                 "* TODO %?\n:PROPERTIES:\n:OPEN: %U\n:LAST: %U\n:END:\n%a\n")
                ("j" "Journal" entry (file+datetree "~/stuff/org/diary.org")
                 "* %?\n:PROPERTIES:\n:OPEN: %U\n:LAST: %U\n:END:\n")
                ("u" "urgent todo" entry (file "~/stuff/org/refile.org")
                 "* TODO %? :urgent:\n:PROPERTIES:\n:OPEN: %U\n:LAST: %U\n:END:\n")
                ("n" "note" entry (file "~/stuff/org/refile.org")
                 "* %?\n:PROPERTIES:\n:OPEN: %U\n:LAST: %U\n:END:\n")
                ("z" "bugz" entry (file+headline "~/stuff/org/bugz.org" "incoming")
                 "* TODO %?\n:PROPERTIES:\n:OPEN: %U\n:LAST:%U\n:END:\n%a\n")
                ("i" "instadev" entry (file+headline "~/stuff/content/ideas.org" "instadev")
                 "* %c\n")
                ("s" "snipz")  
                ("sr" "snipz request" entry (file+headline "~/stuff/org/snipz.org" "incoming")
                 "* TODO %?\n:PROPERTIES:\n:OPEN: %U\n:LAST:%U\n:END:\n%a\n")
                ("sn" "snipz note" entry (file+headline "~/stuff/org/snipz.org" "incoming")
                 "* %?\n:PROPERTIES:\n:OPEN: %U\n:LAST: %U\n:END:\n%c\n")
                ("b" "binding" entry (file+headline "~/stuff/org/snipz.org" "bindings")
                 "* %?\n:PROPERTIES:\n:OPEN: %U\n:LAST: %U\n:END:")
                ("k" "kill ring")
                ("kb" "kill ring body" entry (file "~/stuff/org/refile.org")
                 "* %?\n:PROPERTIES:\n:OPEN: %U\n:LAST: %U\n:END:\n%c")
                ("kh" "kill ring head" entry (file "~/stuff/org/refile.org")
                 "* TODO %c\n:PROPERTIES:\n:OPEN: %U\n:LAST: %U\n:END:\n%?"))))
  
#+end_src

#+results:
| t  | todo (with link) | entry | (file ~/stuff/org/refile.org)                      | * TODO %?\n:PROPERTIES:\n:OPEN: %U\n:LAST: %U\n:END:\n%a\n      |
| j  | Journal          | entry | (file+datetree ~/stuff/org/diary.org)              | * %?\n:PROPERTIES:\n:OPEN: %U\n:LAST: %U\n:END:\n               |
| u  | urgent todo      | entry | (file ~/stuff/org/refile.org)                      | * TODO %? :urgent:\n:PROPERTIES:\n:OPEN: %U\n:LAST: %U\n:END:\n |
| n  | note             | entry | (file ~/stuff/org/refile.org)                      | * %?\n:PROPERTIES:\n:OPEN: %U\n:LAST: %U\n:END:\n               |
| z  | bugz             | entry | (file+headline ~/stuff/org/bugz.org incoming)      | * TODO %?\n:PROPERTIES:\n:OPEN: %U\n:LAST:%U\n:END:\n%a\n       |
| i  | instadev         | entry | (file+headline ~/stuff/content/ideas.org instadev) | * %c\n                                                          |
| s  | snipz            |       |                                                    |                                                                 |
| sr | snipz request    | entry | (file+headline ~/stuff/org/snipz.org incoming)     | * TODO %?\n:PROPERTIES:\n:OPEN: %U\n:LAST:%U\n:END:\n%a\n       |
| sn | snipz note       | entry | (file+headline ~/stuff/org/snipz.org incoming)     | * %?\n:PROPERTIES:\n:OPEN: %U\n:LAST: %U\n:END:\n%c\n           |
| b  | binding          | entry | (file+headline ~/stuff/org/snipz.org bindings)     | * %?\n:PROPERTIES:\n:OPEN: %U\n:LAST: %U\n:END:                 |
| k  | kill ring        |       |                                                    |                                                                 |
| kb | kill ring body   | entry | (file ~/stuff/org/refile.org)                      | * %?\n:PROPERTIES:\n:OPEN: %U\n:LAST: %U\n:END:\n%c             |
| kh | kill ring head   | entry | (file ~/stuff/org/refile.org)                      | * TODO %c\n:PROPERTIES:\n:OPEN: %U\n:LAST: %U\n:END:\n%?        |




*** Refiling
CLOSED: [2012-07-20 Fri 00:20]
:LOGBOOK:
- State "DONE"       from "NEXT"       [2012-07-20 Fri 00:20]
- State "NEXT"       from "TODO"       [2012-07-20 Fri 00:20]
- State "TODO"       from ""           [2012-07-19 Thu 22:43]
:END:

#+begin_src emacs-lisp  
; Targets include this file and any file contributing to the agenda - up to 4 levels deep
(setq org-refile-targets (quote ((nil :maxlevel . 4)
                                 (org-agenda-files :maxlevel . 4))))
; Use full outline paths for refile targets - we file directly with IDO
(setq org-refile-use-outline-path t)
; Targets complete directly with IDO
(setq org-outline-path-complete-in-steps nil)
; Allow refile to create parent tasks with confirmation
(setq org-refile-allow-creating-parent-nodes (quote confirm))
; every header is a refile target
(setq org-refile-target-verify-function nil)
; use IDO
(setq org-completion-use-ido t)

#+end_src

#+results:

*** Agenda view
:PROPERTIES:
		:Effort:   0.45
:OPEN: [2012-07-23 Mon 19:45]
:LAST:  [2012-07-23 Mon 20:24]
:CLOSE: [2012-07-23 Mon 20:24]
:ID: b6b3a794-7836-4259-8b9c-92ce0a35cd24
		:END:

Startup should take this table and create the org-agenda-files list.

#+TBLNAME: agenda-files-table
| stuff           | meta.org                    |                   |
| .emacs.d        | README.org                  |                   |
| stuff           | org                         | refile.org        |
| stuff           | org                         | bugz.org          |
| stuff           | org                         | snipz.org         |
| stuff           | org                         | org.org           |
| stuff           | emacs                       | emacs.org         |
| stuff           | sys                         | sys.org           |
| stuff           | biz                         | scarce.org        |
| stuff           | site                        | landing.org       |
| stuff           | site                        | scarcecapital.org |
| stuff           | content                     | life.org          |
| stuff           | content                     | writing.org       |
| stuff           | dev                         | webdev.org        |
| stuff           | emacs                       | bindings.org      |
| stuff           | sys                         | git.org           |
| stuff           | factor                      | factor.org        |
| stuff           | dev                         | jsdev.org         |
| stuff           | content                     | ideas.org         |
| git             | emfx_R                      | emfx.org          |
| git             | emfx_R                      | volatility.org    |
| git             | emfx_R                      | rdev.org          |
| git             | emfx_R                      | xkcd.org          |
| emfx            | README.org                  |                   |

- function to reset org-agenda-files based on the above table of directories
  and files
  #+begin_src emacs-lisp :var table=agenda-files-table
    (setq clean-table
          (delete nil  
                  (loop for line in table
                        collect 
                        (delete "" (delete-dups line)))))
    
    (setq org-agenda-files 
          (mapcar
           (lambda (x) 
             (concat "~/"
                     (mapconcat
                      'eval x "/")))
           clean-table))
  #+end_src

  #+results:
  | ~/stuff/meta.org | ~/.emacs.d/README.org | ~/stuff/org/refile.org | ~/stuff/org/bugz.org | ~/stuff/org/snipz.org | ~/stuff/org/org.org | ~/stuff/emacs/emacs.org | ~/stuff/sys/sys.org | ~/stuff/biz/scarce.org | ~/stuff/site/landing.org | ~/stuff/site/scarcecapital.org | ~/stuff/content/life.org | ~/stuff/content/writing.org | ~/stuff/dev/webdev.org | ~/stuff/emacs/bindings.org | ~/stuff/sys/git.org | ~/stuff/factor/factor.org | ~/stuff/dev/jsdev.org | ~/stuff/content/ideas.org | ~/git/emfx_R/emfx.org | ~/git/emfx_R/volatility.org | ~/git/emfx_R/rdev.org | ~/git/emfx_R/xkcd.org | ~/emfx/README.org |



- (Manual) Agenda Files (turned off)
  #+begin_src emacs-lisp :tangle no
    ;; the entire directory (hand edit this)
    (setq org-agenda-files (quote ("~/stuff/org/refile.org"
                                   "~/stuff/org/org.org"
                                   "~/stuff/org/bugz.org"
                                   "~/stuff/org/snipz.org"
                                   "~/stuff/biz/scarce.org"
                                   "~/stuff/meta.org"
                                   "~/stuff/content/life.org"
                                   "~/stuff/content/writing.org"
                                   "~/stuff/emacs/emacs.org"
                                   "~/stuff/emacs/bindings.org"
                                   "~/.emacs.d/tonyday.org"
                                   "~/.emacs.d/starter-kit-tonyday-org.org"
                                   "~/stuff/sys/sys.org"
                                   "~/stuff/sys/migrate.org"
                                   "~/stuff/site/scarcecapital.org"
                                   "~/stuff/dev/webdev.org"
                                   "~/stuff/sys/git.org"
                                   "~/stuff/factor/momentum/qic.org"
                                   "~/stuff/factor/emfx.org"
                                   "~/stuff/factor/factor.org"
                                   "~/emfx/emfx.org"
                                   "~/dotemacs-mashup/README.org"
                                   "~/stuff/dev/rdev.org"
                                   "~/stuff/dev/jsdev.org"
                                   "~/stuff/dev/webdev.org"
                                   "~/stuff/content/quant.org"
                                   "~/stuff/content/ideas.org")))
    
  #+end_src

  #+results:
  | ~/stuff/org/refile.org | ~/stuff/org/org.org | ~/stuff/org/bugz.org | ~/stuff/org/snipz.org | ~/stuff/biz/scarce.org | ~/stuff/meta.org | ~/stuff/content/life.org | ~/stuff/content/writing.org | ~/stuff/emacs/emacs.org | ~/stuff/emacs/bindings.org | ~/.emacs.d/tonyday.org | ~/.emacs.d/starter-kit-tonyday-org.org | ~/stuff/sys/sys.org | ~/stuff/sys/migrate.org | ~/stuff/site/scarcecapital.org | ~/stuff/dev/webdev.org | ~/stuff/sys/git.org | ~/stuff/factor/momentum/qic.org | ~/stuff/factor/emfx.org | ~/stuff/factor/factor.org | ~/emfx/emfx.org | ~/dotemacs-mashup/README.org | ~/stuff/dev/rdev.org | ~/stuff/dev/jsdev.org | ~/stuff/dev/webdev.org | ~/stuff/content/quant.org | ~/stuff/content/ideas.org |

- disable =C-c [=
  I adopt the same system as =norang=.  It becomes difficult to
  remember what's on and not on the agenda
 #+begin_src emacs-lisp
   ;; Disable C-c [ and C-c ] in org-mode
   (add-hook 'org-mode-hook
             (lambda ()
               ;; Undefine C-c [ and C-c ] since this breaks my
               ;; org-agenda files when directories are include It
               ;; expands the files in the directories individually
               (org-defkey org-mode-map "\C-c["    'undefined)
               (org-defkey org-mode-map "\C-c]"    'undefined))
             'append)
  #+end_src




Standard settings
#+begin_src emacs-lisp 
  ;; Compact the block agenda view
  (setq org-agenda-compact-blocks t)
  
  ;; Do not dim blocked tasks
  (setq org-agenda-dim-blocked-tasks nil)
  (setq org-agenda-span 'day)
  (setq org-stuck-projects (quote ("" nil nil "")))

#+end_src

#+results:
|   | nil | nil |   |

- Custom agenda
  This custom view is lidted straight from =norang=.  I have no idea
  how it does what it does, nor what it actually does, but it works
  for me.
  #+begin_src emacs-lisp :tangle yes
    ;; Custom agenda command definitions
    (setq org-agenda-custom-commands
          (quote (("N" "Notes" tags "NOTE"
                   ((org-agenda-overriding-header "Notes")
                    (org-tags-match-list-sublevels t)))
                  ("h" "Habits" tags-todo "STYLE=\"habit\""
                   ((org-agenda-overriding-header "Habits")
                    (org-agenda-sorting-strategy
                     '(todo-state-down effort-up category-keep))))
                  (" " "Agenda"
                   ((agenda "" nil)
                    (tags "REFILE"
                          ((org-agenda-overriding-header "Tasks to Refile")
                           (org-tags-match-list-sublevels nil)))
                    (tags-todo "-CANCELLED/!"
                               ((org-agenda-overriding-header "Stuck Projects")
                                (org-agenda-skip-function 'bh/skip-non-stuck-projects)))
                    (tags-todo "-WAITING-CANCELLED/!NEXT"
                               ((org-agenda-overriding-header "Next Tasks")
                                (org-agenda-skip-function 'bh/skip-projects-and-habits-and-single-tasks)
                                (org-agenda-todo-ignore-scheduled t)
                                (org-agenda-todo-ignore-deadlines t)
                                (org-tags-match-list-sublevels t)
                                (org-agenda-sorting-strategy
                                 '(todo-state-down effort-up category-keep))))
                    (tags-todo "-REFILE-CANCELLED/!-HOLD-WAITING"
                               ((org-agenda-overriding-header "Tasks")
                                (org-agenda-skip-function 'bh/skip-project-tasks-maybe)
                                (org-agenda-todo-ignore-scheduled t)
                                (org-agenda-todo-ignore-deadlines t)
                                (org-agenda-sorting-strategy
                                 '(category-keep))))
                    (tags-todo "-CANCELLED/!"
                               ((org-agenda-overriding-header "Projects")
                                (org-agenda-skip-function 'bh/skip-non-projects)
                                (org-agenda-sorting-strategy
                                 '(category-keep))))
                    (tags-todo "-CANCELLED/!WAITING|HOLD"
                               ((org-agenda-overriding-header "Waiting and Postponed Tasks")
                                (org-tags-match-list-sublevels nil)
                                (org-agenda-todo-ignore-scheduled 'future)
                                (org-agenda-todo-ignore-deadlines 'future)))
                    (tags "-REFILE/"
                          ((org-agenda-overriding-header "Tasks to Archive")
                           (org-agenda-skip-function 'bh/skip-non-archivable-tasks))))
                   nil)
                  ("r" "Tasks to Refile" tags "REFILE"
                   ((org-agenda-overriding-header "Tasks to Refile")
                    (org-tags-match-list-sublevels nil)))
                  ("#" "Stuck Projects" tags-todo "-CANCELLED/!"
                   ((org-agenda-overriding-header "Stuck Projects")
                    (org-agenda-skip-function 'bh/skip-non-stuck-projects)))
                  ("n" "Next Tasks" tags-todo "-WAITING-CANCELLED/!NEXT"
                   ((org-agenda-overriding-header "Next Tasks")
                    (org-agenda-skip-function 'bh/skip-projects-and-habits-and-single-tasks)
                    (org-agenda-todo-ignore-scheduled t)
                    (org-agenda-todo-ignore-deadlines t)
                    (org-tags-match-list-sublevels t)
                    (org-agenda-sorting-strategy
                     '(todo-state-down effort-up category-keep))))
                  ("R" "Tasks" tags-todo "-REFILE-CANCELLED/!-HOLD-WAITING"
                   ((org-agenda-overriding-header "Tasks")
                    (org-agenda-skip-function 'bh/skip-project-tasks-maybe)
                    (org-agenda-sorting-strategy
                     '(category-keep))))
                  ("p" "Projects" tags-todo "-CANCELLED/!"
                   ((org-agenda-overriding-header "Projects")
                    (org-agenda-skip-function 'bh/skip-non-projects)
                    (org-agenda-sorting-strategy
                     '(category-keep))))
                  ("w" "Waiting Tasks" tags-todo "-CANCELLED/!WAITING|HOLD"
                   ((org-agenda-overriding-header "Waiting and Postponed tasks"))
                   (org-tags-match-list-sublevels nil))
                  ("A" "Tasks to Archive" tags "-REFILE/"
                   ((org-agenda-overriding-header "Tasks to Archive")
                    (org-agenda-skip-function 'bh/skip-non-archivable-tasks))))))
  #+end_src

  #+results:
  | N | Notes            | tags                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | NOTE                                                                                                                                                                                                                                                                                                                                          | ((org-agenda-overriding-header Notes) (org-tags-match-list-sublevels t))                                                                                                                                                                                                                                                |                                                              |                                     |
  | h | Habits           | tags-todo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | STYLE="habit"                                                                                                                                                                                                                                                                                                                                 | ((org-agenda-overriding-header Habits) (org-agenda-sorting-strategy (quote (todo-state-down effort-up category-keep))))                                                                                                                                                                                                 |                                                              |                                     |
  |   | Agenda           | ((agenda  nil) (tags REFILE ((org-agenda-overriding-header Tasks to Refile) (org-tags-match-list-sublevels nil))) (tags-todo -CANCELLED/! ((org-agenda-overriding-header Stuck Projects) (org-agenda-skip-function (quote bh/skip-non-stuck-projects)))) (tags-todo -WAITING-CANCELLED/!NEXT ((org-agenda-overriding-header Next Tasks) (org-agenda-skip-function (quote bh/skip-projects-and-habits-and-single-tasks)) (org-agenda-todo-ignore-scheduled t) (org-agenda-todo-ignore-deadlines t) (org-tags-match-list-sublevels t) (org-agenda-sorting-strategy (quote (todo-state-down effort-up category-keep))))) (tags-todo -REFILE-CANCELLED/!-HOLD-WAITING ((org-agenda-overriding-header Tasks) (org-agenda-skip-function (quote bh/skip-project-tasks-maybe)) (org-agenda-todo-ignore-scheduled t) (org-agenda-todo-ignore-deadlines t) (org-agenda-sorting-strategy (quote (category-keep))))) (tags-todo -CANCELLED/! ((org-agenda-overriding-header Projects) (org-agenda-skip-function (quote bh/skip-non-projects)) (org-agenda-sorting-strategy (quote (category-keep))))) (tags-todo -CANCELLED/!WAITING | HOLD ((org-agenda-overriding-header Waiting and Postponed Tasks) (org-tags-match-list-sublevels nil) (org-agenda-todo-ignore-scheduled (quote future)) (org-agenda-todo-ignore-deadlines (quote future)))) (tags -REFILE/ ((org-agenda-overriding-header Tasks to Archive) (org-agenda-skip-function (quote bh/skip-non-archivable-tasks))))) | nil                                                                                                                                                                                                                                                                                                                     |                                                              |                                     |
  | r | Tasks to Refile  | tags                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | REFILE                                                                                                                                                                                                                                                                                                                                        | ((org-agenda-overriding-header Tasks to Refile) (org-tags-match-list-sublevels nil))                                                                                                                                                                                                                                    |                                                              |                                     |
  | # | Stuck Projects   | tags-todo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | -CANCELLED/!                                                                                                                                                                                                                                                                                                                                  | ((org-agenda-overriding-header Stuck Projects) (org-agenda-skip-function (quote bh/skip-non-stuck-projects)))                                                                                                                                                                                                           |                                                              |                                     |
  | n | Next Tasks       | tags-todo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | -WAITING-CANCELLED/!NEXT                                                                                                                                                                                                                                                                                                                      | ((org-agenda-overriding-header Next Tasks) (org-agenda-skip-function (quote bh/skip-projects-and-habits-and-single-tasks)) (org-agenda-todo-ignore-scheduled t) (org-agenda-todo-ignore-deadlines t) (org-tags-match-list-sublevels t) (org-agenda-sorting-strategy (quote (todo-state-down effort-up category-keep)))) |                                                              |                                     |
  | R | Tasks            | tags-todo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | -REFILE-CANCELLED/!-HOLD-WAITING                                                                                                                                                                                                                                                                                                              | ((org-agenda-overriding-header Tasks) (org-agenda-skip-function (quote bh/skip-project-tasks-maybe)) (org-agenda-sorting-strategy (quote (category-keep))))                                                                                                                                                             |                                                              |                                     |
  | p | Projects         | tags-todo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | -CANCELLED/!                                                                                                                                                                                                                                                                                                                                  | ((org-agenda-overriding-header Projects) (org-agenda-skip-function (quote bh/skip-non-projects)) (org-agenda-sorting-strategy (quote (category-keep))))                                                                                                                                                                 |                                                              |                                     |
  | w | Waiting Tasks    | tags-todo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | -CANCELLED/!WAITING                                                                                                                                                                                                                                                                                                                           | HOLD                                                                                                                                                                                                                                                                                                                    | ((org-agenda-overriding-header Waiting and Postponed tasks)) | (org-tags-match-list-sublevels nil) |
  | A | Tasks to Archive | tags                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | -REFILE/                                                                                                                                                                                                                                                                                                                                      | ((org-agenda-overriding-header Tasks to Archive) (org-agenda-skip-function (quote bh/skip-non-archivable-tasks)))                                                                                                                                                                                                       |                                                              |                                     |




*** Agenda Keys
:PROPERTIES:
:OPEN: [2012-07-23 Mon 20:41]
:LAST: NEXT [2012-08-01 Wed 15:08]
:END:

Most of these agenda commands are from =norang=.  The defuns are
defined [[file:starter-kit-zyg-defuns-org.org::*%3Dnorang%3D%20defuns][here]].

#+begin_src emacs-lisp 
(add-hook 'org-agenda-mode-hook
          (lambda ()
            (define-key org-agenda-mode-map "q" 'bury-buffer))
          'append)
(add-hook 'org-agenda-mode-hook
          '(lambda () (org-defkey org-agenda-mode-map "F" 'bh/restrict-to-file-or-follow))
          'append)
(add-hook 'org-agenda-mode-hook
          '(lambda () (org-defkey org-agenda-mode-map "W" 'bh/widen))
          'append)
(add-hook 'org-agenda-mode-hook
          '(lambda () (org-defkey org-agenda-mode-map "N" 'bh/narrow-to-subtree))
          'append)
(add-hook 'org-agenda-mode-hook
          '(lambda () (org-defkey org-agenda-mode-map "P" 'bh/narrow-to-project))
          'append)
(add-hook 'org-agenda-mode-hook
          '(lambda () (org-defkey org-agenda-mode-map "U" 'bh/narrow-up-one-level))
          'append)
(add-hook 'org-agenda-mode-hook
          '(lambda () (org-defkey org-agenda-mode-map "\C-c\C-x<" 'bh/set-agenda-restriction-lock))
          'append)
#+end_src

#+results:
| lambda | nil | (define-key org-agenda-mode-map q (quote bury-buffer))                        |
| lambda | nil | (org-defkey org-agenda-mode-map F (quote bh/restrict-to-file-or-follow))      |
| lambda | nil | (org-defkey org-agenda-mode-map W (quote bh/widen))                           |
| lambda | nil | (org-defkey org-agenda-mode-map N (quote bh/narrow-to-subtree))               |
| lambda | nil | (org-defkey org-agenda-mode-map P (quote bh/narrow-to-project))               |
| lambda | nil | (org-defkey org-agenda-mode-map U (quote bh/narrow-up-one-level))             |
| lambda | nil | (org-defkey org-agenda-mode-map < (quote bh/set-agenda-restriction-lock)) |
| lambda | nil | (hl-line-mode 1)                                                              |

*** Agenda Settings - Miscellaneous
:PROPERTIES:
:OPEN: [2012-08-01 Wed 13:57]
:CLOSE: [2012-08-01 Wed 13:57]
:LAST:  [2012-08-01 Wed 13:57]
:END:

These follow the =norang= suggestions  
#+begin_src emacs-lisp 
;; Always hilight the current agenda line
(add-hook 'org-agenda-mode-hook
          '(lambda () (hl-line-mode 1))
          'append)

;; Keep tasks with dates on the global todo lists
(setq org-agenda-todo-ignore-with-date nil)

;; Keep tasks with deadlines on the global todo lists
(setq org-agenda-todo-ignore-deadlines nil)

;; Keep tasks with scheduled dates on the global todo lists
(setq org-agenda-todo-ignore-scheduled nil)

;; Keep tasks with timestamps on the global todo lists
(setq org-agenda-todo-ignore-timestamp nil)

;; Remove completed deadline tasks from the agenda view
(setq org-agenda-skip-deadline-if-done t)

;; Remove completed scheduled tasks from the agenda view
(setq org-agenda-skip-scheduled-if-done t)

;; Remove completed items from search results
(setq org-agenda-skip-timestamp-if-done t)

(setq org-agenda-include-diary nil)
(setq org-agenda-diary-file (expand-file-name "~/org/diary.org"))

(setq org-agenda-insert-diary-extract-time t)

;; Include agenda archive files when searching for things
(setq org-agenda-text-search-extra-files (quote (agenda-archives)))

;; Show all future entries for repeating tasks
(setq org-agenda-repeating-timestamp-show-all t)

;; Show all agenda dates - even if they are empty
(setq org-agenda-show-all-dates t)

;; Start the weekly agenda on Monday
(setq org-agenda-start-on-weekday 1)

;; Enable display of the time grid so we can see the marker for the current time
(setq org-agenda-time-grid (quote ((daily today remove-match)
                                   #("----------------" 0 16 (org-heading t))
                                   (830 1000 1200 1300 1500 1700))))

;; Display tags farther right
(setq org-agenda-tags-column -102)

;; Keep filters in place
(setq org-agenda-persistent-filter t)




#+end_src

#+results:
: t




*** Agenda sort from =norang=

Defuns are defined [[file:starter-kit-zyg-defuns-org.org::*%3Dnorang%3D%20defuns][here]]. 
#+begin_src emacs-lisp
  
  ;; Sorting order for tasks on the agenda
  (setq org-agenda-sorting-strategy
        (quote ((agenda habit-down time-up user-defined-up priority-down effort-up category-keep)
                (todo category-up priority-down effort-up)
                (tags category-up priority-down effort-up)
                (search category-up))))
  ;;
  ;; Agenda sorting functions
  ;;
  (setq org-agenda-cmp-user-defined 'bh/agenda-sort)
#+end_src

#+results:
: bh/agenda-sort

*** Tags

#+begin_src emacs-lisp 

; Tags with fast selection keys
(setq org-tag-alist (quote (("urgent" . ?u)
                            ("bill" . ?b)
                            ("scarce" . ?s)
                            ("crypt" . ?c)
                            ("emacs" . ?e))))
                            
; Allow setting single tags without the menu
(setq org-fast-tag-selection-single-key (quote expert))

; For tag searches ignore tasks with scheduled and deadline dates
(setq org-agenda-tags-todo-honor-ignore-options nil)

#+end_src

#+results:

*** Archiving
:LOGBOOK:
- State "DONE"       from "NEXT"       [2012-07-19 Thu 23:19]
- State "NEXT"       from "TODO"       [2012-07-19 Thu 23:19]
- State "TODO"       from ""           [2012-07-19 Thu 23:19]
:END:

Anything with a =DONE= todo tag is a valid archiving candidate.
Though more often than not I'm going to set a section heading back to
=""= once I'm done.

#+begin_src emacs-lisp 
(setq org-archive-mark-done nil)
(setq org-archive-location "%s_archive::* Archived Tasks")
#+end_src

#+results:
: %s_archive::* Archived Tasks

*** Code Blocks
:PROPERTIES:
:OPEN: [2012-07-23 Mon 19:52]
:LAST: TODO [2012-07-23 Mon 19:52]
:END:

- lowercase results
  #+begin_src emacs-lisp 
  (setq org-babel-results-keyword "results")
  #+end_src

  #+results:
  : results

- languages used
  #+begin_src emacs-lisp 
    (org-babel-do-load-languages
       (quote org-babel-load-languages)
       (quote ((emacs-lisp . t)
               (sh . t)
               (gnuplot . t)
               (org . t)
               (octave . t)
               (js . t)
               (R . t))))
  #+end_src

  #+results:
  | (emacs-lisp . t) | (sh . t) | (gnuplot . t) | (org . t) | (octave . t) |

- Don't cache me
  #+begin_src emacs-lisp 
    (setq org-babel-default-header-args
    (cons '(:cache . "no")
    (assq-delete-all :cache org-babel-default-header-args)))
  #+end_src

  #+results:
  | (:cache . no) | (:session . *Inferior Octave*) | (:results . value) | (:results . replace) | (:exports . code) | (:noweb . no) | (:hlines . no) | (:tangle . no) | (:padnewline . yes) |

- Don't prompt me
  #+begin_src emacs-lisp 
  (setq org-confirm-babel-evaluate nil)
  #+end_src

  #+results:

- do not re-evaluate on export
  #+begin_src emacs-lisp 
  (setq org-export-babel-evaluate nil)
  #+end_src

  #+results:

- Use the current window for C-c ' source editing
  #+begin_src emacs-lisp 
  (setq org-src-window-setup 'current-window)
  #+end_src

  #+results:
  : current-window

- Always look your best
  #+begin_src emacs-lisp 
  (setq org-src-fontify-natively t)
  #+end_src

  #+results:
  : t

- I wish I'd known about this before.
  #+begin_src emacs-lisp 
  (setq org-src-tab-acts-natively t)
  #+end_src

  #+results:
  : t

  

*** Setting to get Octave Working
:PROPERTIES:
:ID: b142296d-b21d-4f4b-a462-3404ff6b4c57
:END:

- Results are value (needed for octave)
  #+begin_src emacs-lisp 
  (setq org-babel-default-header-args
       (cons '(:results . "value") org-babel-default-header-args)) 
  #+end_src

  #+results:
  | (:results . value) | (:cache . no) | (:session . *Inferior Octave*) | (:results . value) | (:results . replace) | (:exports . code) | (:noweb . no) | (:hlines . no) | (:tangle . no) | (:padnewline . yes) |

- [ ] inline images break my windows emacs 
  #+begin_src emacs-lisp 
  (setq org-startup-with-inline-images nil)
  #+end_src

  #+results:

- Single session for Octave
  - [ ] breaks other languages of course as it's a global variable
  - turning this off
  #+begin_src emacs-lisp :tangle no
  ; Run octave in the same session.  Without this set, octave opens
  ; and closes on every evaluation.
  (setq org-babel-default-header-args
         (cons '(:session . "*Inferior Octave*")
         (assq-delete-all :session org-babel-default-header-args)))
  #+end_src

  #+results:
  | (:session . *Inferior Octave*) | (:results . value) | (:cache . no) | (:results . value) | (:results . replace) | (:exports . code) | (:noweb . no) | (:hlines . no) | (:tangle . no) | (:padnewline . yes) |

- tangle octave files with a .m suffix
  #+begin_src emacs-lisp 
  (add-to-list 'org-babel-tangle-lang-exts '("octave" . "m"))
  #+end_src

  #+results:
  | (octave . m) | (emacs-lisp . el) |

- sub-scripts might mess with octave
  #+begin_src emacs-lisp 
  (setq org-use-sub-superscripts nil)
  #+end_src

  #+results:


*** Export settings
:LOGBOOK:
		 - State "DONE"       from "TODO"       [2012-05-29 Tue 09:10]
		 :END:
:PROPERTIES:
:Effort: 5:00
:ID: 85ec9756-18b2-4240-a021-7cfa8e6f718b
:END:

HTML exported using org looks so clean and stylish.

- no post-amble thanks
  #+begin_src emacs-lisp 
  (setq org-export-html-postamble nil)
  #+end_src

  #+results:

  
- Inline images in HTML instead of producting links to the image
  #+begin_src emacs-lisp 
  (setq org-export-html-inline-images t)
  #+end_src

  #+results:
  : t

- Using an external style file
  #+begin_src emacs-lisp 
    (setq org-export-html-style "<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\"/>")
    (setq org-export-html-style-include-default nil)
  #+end_src

  #+results:

- Do not generate internal css formatting for HTML exports
  - [ ] try this out M-x org-export-htmlize-generate-css
  #+begin_src emacs-lisp 
  (setq org-export-htmlize-output-type (quote css))
  #+end_src

  #+results:
  : css

- Export with LaTeX fragments
  - [ ] dollar dollar bug
  #+begin_src emacs-lisp 
  (setq org-export-with-LaTeX-fragments t)
  #+end_src

  #+results:
  : t

- html decl
  #+begin_src emacs-lisp 
  (setq org-export-html-xml-declaration (quote (("html" . "")
                                                ("was-html" . "<?xml version=\"1.0\" encoding=\"%s\"?>")
                                                ("php" . "<?php echo \"<?xml version=\\\"1.0\\\" encoding=\\\"%s\\\" ?>\"; ?>"))))
  #+end_src

  #+results:
  | (html . ) | (was-html . <?xml version="1.0" encoding="%s"?>) | (php . <?php echo "<?xml version=\"1.0\" encoding=\"%s\" ?>"; ?>) |

- allow BIND to do its thing
  #+begin_src emacs-lisp 
  (setq org-export-allow-BIND t)
  #+end_src

  #+results:
  : t

- timestamps outside drawers are evil.
  #+begin_src emacs-lisp 
  (setq org-export-with-timestamps nil)
  #+end_src

  #+results:


*** Publishing
:PROPERTIES:
:OPEN: [2012-07-23 Mon 20:14]
:LAST:     [2012-10-11 Thu 13:31]
:CLOSE:    [2012-10-11 Thu 13:31]
:END:

This is still in test mode.

#+begin_src emacs-lisp 
  ;tmp - http://www.scarcecapital.com/qic
  (setq org-publish-project-alist
        ; mom-org are the org-files that generate the content
        ; mom-extra are images and css files that need to be included
        ; mom is the top-level project that gets published
        (quote (("mom-report-org"
                 :base-directory "~/projects/qic/momentum/draft"
                 :publishing-directory "~/pub/report"
                 ; :publishing-directory "/ssh:www-data@www:~/www.scarcecapital.com/tmp"
                 :recursive t
                 :section-numbers nil
                 :table-of-contents nil
                 :base-extension "org"
                 :publishing-function (org-publish-org-to-html org-publish-org-to-org)
                 :style "<link rel=\"stylesheet\" href=\"scarce.css\" type=\"text/css\" />"
                 :plain-source t
                 :htmlized-source t
                 :style-include-default nil
                 :auto-sitemap t
                 :sitemap-filename "index.html"
                 :sitemap-title "Momentum Report"
                 :sitemap-style "tree"
                 :author-info t
                 :creator-info t)
                ("mom-report-extra"
                 :base-directory "~/projects/qic/momentum/draft"
                 :publishing-directory "~/pub/report"
                 :base-extension "css\\|pdf\\|png\\|jpg\\|gif"
                 :publishing-function org-publish-attachment
                 :recursive t
                 :author nil)
                ("mom-report"
                 :components ("mom-report-org" "mom-report-extra"))
                ; tmp for quick testing
                ("tmp-org"
                 :base-directory "~/tmp/publish"
                 :publishing-directory "~/pub/tmp"
                 ; :publishing-directory "/ssh:www-data@www:~/www.scarcecapital.com/tmp"
                 :recursive t
                 :section-numbers nil
                 :table-of-contents nil
                 :base-extension "org"
                 :publishing-function (org-publish-org-to-html org-publish-org-to-org)
                 ;:style "<link rel=\"stylesheet\" href=\"http://scarcecapital.com/tmp/org.css\" type=\"text/css\" />"
                 ; I assume you can then just put the stylesheet in the directory (tmp) and all is cool
                 :style "<link rel=\"stylesheet\" href=\"org.css\" type=\"text/css\" />"
                 :plain-source t
                 :htmlized-source t
                 :style-include-default nil
                 :auto-sitemap t
                 :sitemap-filename "index.html"
                 :sitemap-title "Test Publishing Environment"
                 :sitemap-style "tree"
                 :author-info t
                 :creator-info t)
                ("tmp-extra"
                 :base-directory "~/tmp/publish/"
                 :publishing-directory "~/pub/tmp"
                 :base-extension "css\\|pdf\\|png\\|jpg\\|gif\\|el"
                 :publishing-function org-publish-attachment
                 :recursive t
                 :author nil)
                ("tmp"
                 :components ("tmp-org" "tmp-extra"))
                ; mom-dev is a testing version
                ("mom-dev-org"
                 :base-directory "~/projects/momentum/dev"
                 :publishing-directory "~/pub/dev"
                 ; :publishing-directory "/ssh:www-data@www:~/www.scarcecapital.com/tmp"
                 :recursive t
                 :section-numbers nil
                 :table-of-contents nil
                 :base-extension "org"
                 :publishing-function (org-publish-org-to-html org-publish-org-to-org)
                 :style "<link rel=\"stylesheet\" href=\"http://scarcecapital.com/tmp/org.css\" type=\"text/css\" />"
                 :plain-source t
                 :htmlized-source t
                 :style-include-default nil
                 :auto-sitemap t
                 :sitemap-filename "index.html"
                 :sitemap-title "Momemtum Development"
                 :sitemap-style "tree"
                 :author-info t
                 :creator-info t)
                ("mom-dev-extra"
                 :base-directory "~/projects/momentum/dev"
                 :publishing-directory "~/pub/dev"
                 :base-extension "css\\|pdf\\|png\\|jpg\\|gif"
                 :publishing-function org-publish-attachment
                 :recursive t
                 :author nil)
                ("mom-dev"
                 :components ("mom-dev-org" "mom-dev-extra")))))

#+end_src

#+results:
| mom-report-org   | :base-directory | ~/projects/qic/momentum/draft     | :publishing-directory | ~/pub/report | :recursive      | t    | :section-numbers | nil  | :table-of-contents | nil  | :base-extension      | org                    | :publishing-function   | (org-publish-org-to-html org-publish-org-to-org) | :style  | <link rel="stylesheet" href="scarce.css" type="text/css" />                           | :plain-source | t | :htmlized-source | t | :style-include-default | nil | :auto-sitemap | t | :sitemap-filename | index.html | :sitemap-title | Momentum Report             | :sitemap-style | tree | :author-info | t | :creator-info | t |
| mom-report-extra | :base-directory | ~/projects/qic/momentum/draft     | :publishing-directory | ~/pub/report | :base-extension | css\ | pdf\             | png\ | jpg\               | gif  | :publishing-function | org-publish-attachment | :recursive             | t                                                | :author | nil                                                                                   |               |   |                  |   |                        |     |               |   |                   |            |                |                             |                |      |              |   |               |   |
| mom-report       | :components     | (mom-report-org mom-report-extra) |                       |              |                 |      |                  |      |                    |      |                      |                        |                        |                                                  |         |                                                                                       |               |   |                  |   |                        |     |               |   |                   |            |                |                             |                |      |              |   |               |   |
| tmp-org          | :base-directory | ~/tmp/publish                     | :publishing-directory | ~/pub/tmp    | :recursive      | t    | :section-numbers | nil  | :table-of-contents | nil  | :base-extension      | org                    | :publishing-function   | (org-publish-org-to-html org-publish-org-to-org) | :style  | <link rel="stylesheet" href="org.css" type="text/css" />                              | :plain-source | t | :htmlized-source | t | :style-include-default | nil | :auto-sitemap | t | :sitemap-filename | index.html | :sitemap-title | Test Publishing Environment | :sitemap-style | tree | :author-info | t | :creator-info | t |
| tmp-extra        | :base-directory | ~/tmp/publish/                    | :publishing-directory | ~/pub/tmp    | :base-extension | css\ | pdf\             | png\ | jpg\               | gif\ | el                   | :publishing-function   | org-publish-attachment | :recursive                                       | t       | :author                                                                               | nil           |   |                  |   |                        |     |               |   |                   |            |                |                             |                |      |              |   |               |   |
| tmp              | :components     | (tmp-org tmp-extra)               |                       |              |                 |      |                  |      |                    |      |                      |                        |                        |                                                  |         |                                                                                       |               |   |                  |   |                        |     |               |   |                   |            |                |                             |                |      |              |   |               |   |
| mom-dev-org      | :base-directory | ~/projects/momentum/dev           | :publishing-directory | ~/pub/dev    | :recursive      | t    | :section-numbers | nil  | :table-of-contents | nil  | :base-extension      | org                    | :publishing-function   | (org-publish-org-to-html org-publish-org-to-org) | :style  | <link rel="stylesheet" href="http://scarcecapital.com/tmp/org.css" type="text/css" /> | :plain-source | t | :htmlized-source | t | :style-include-default | nil | :auto-sitemap | t | :sitemap-filename | index.html | :sitemap-title | Momemtum Development        | :sitemap-style | tree | :author-info | t | :creator-info | t |
| mom-dev-extra    | :base-directory | ~/projects/momentum/dev           | :publishing-directory | ~/pub/dev    | :base-extension | css\ | pdf\             | png\ | jpg\               | gif  | :publishing-function | org-publish-attachment | :recursive             | t                                                | :author | nil                                                                                   |               |   |                  |   |                        |     |               |   |                   |            |                |                             |                |      |              |   |               |   |
| mom-dev          | :components     | (mom-dev-org mom-dev-extra)       |                       |              |                 |      |                  |      |                    |      |                      |                        |                        |                                                  |         |                                                                                       |               |   |                  |   |                        |     |               |   |                   |            |                |                             |                |      |              |   |               |   |


*** Visuals

Various visual stylistic choices 
#+begin_src emacs-lisp 
  (setq org-hide-leading-stars nil)
  (setq org-startup-indented t)
  (setq org-cycle-separator-lines 0)
  (setq org-blank-before-new-entry (quote ((heading)
                                           (plain-list-item . auto))))

  (setq org-emphasis-alist (quote (("*" bold "<b>" "</b>")
                                   ("/" italic "<i>" "</i>")
                                   ("_" underline "<span style=\"text-decoration:underline;\">" "</span>")
                                   ("=" org-code "<code>" "</code>" verbatim)
                                   ("~" org-verbatim "<code>" "</code>" verbatim))))
  
#+end_src

#+results:
| * | bold         | <b>                                       | </b>    |          |
| / | italic       | <i>                                       | </i>    |          |
| _ | underline    | <span style="text-decoration:underline;"> | </span> |          |
| = | org-code     | <code>                                    | </code> | verbatim |
| ~ | org-verbatim | <code>                                    | </code> | verbatim |

*** Action Modification

Various stylistic choices 
#+begin_src emacs-lisp 
(setq org-return-follows-link t)
#+end_src

#+results:
: t


*** Special Key

#+begin_src emacs-lisp :tangle yes
  (setq org-special-ctrl-a/e 'reversed)
  (setq org-special-ctrl-k t)
  (setq org-yank-adjusted-subtrees t)
#+end_src

#+results:
: t

 
*** Speed keys
:PROPERTIES:
:CUSTOM_ID: speed-keys
:END:
Speed commands enable single-letter commands in Org-mode files when
the point is at the beginning of a headline, or at the beginning of a
code block.

See the =org-speed-commands-default= variable for a list of the keys
and commands enabled at the beginning of headlines.  All code blocks
are available at the beginning of a code block, the following key
sequence =C-c C-v h= (bound to `=org-babel-describe-bindings=') will
display a list of the code blocks commands and their related keys.

#+begin_src emacs-lisp
(setq org-use-speed-commands t)
(setq org-speed-commands-user (quote (("0" . ignore)
                                        ("1" . ignore)
                                        ("2" . ignore)
                                        ("3" . ignore)
                                        ("4" . ignore)
                                        ("5" . ignore)
                                        ("6" . ignore)
                                        ("7" . ignore)
                                        ("8" . ignore)
                                        ("9" . ignore)
  
                                        ("a" . ignore)
                                        ("d" . ignore)
                                        ("h" . bh/hide-other)
                                        ("i" progn
                                         (forward-char 1)
                                         (call-interactively 'org-insert-heading-respect-content))
                                        ("k" . org-kill-note-or-show-branches)
                                        ("l" . ignore)
                                        ("m" . ignore)
                                        ("q" . bh/show-org-agenda)
                                        ("r" . ignore)
                                        ("s" . org-save-all-org-buffers)
                                        ("w" . org-refile)
                                        ("x" . ignore)
                                        ("y" . ignore)
                                        ("z" . org-add-note)
  
                                        ("A" . ignore)
                                        ("B" . ignore)
                                        ("E" . ignore)
                                        ("F" . bh/restrict-to-file-or-follow)
                                        ("G" . ignore)
                                        ("H" . ignore)
                                        ("J" . org-clock-goto)
                                        ("K" . ignore)
                                        ("L" . ignore)
                                        ("M" . ignore)
                                        ("N" . bh/narrow-to-subtree)
                                        ("P" . bh/narrow-to-project)
                                        ("Q" . ignore)
                                        ("R" . ignore)
                                        ("S" . ignore)
                                        ("T" . bh/org-todo)
                                        ("U" . bh/narrow-up-one-level)
                                        ("V" . ignore)
                                        ("W" . bh/widen)
                                        ("X" . ignore)
                                        ("Y" . ignore)
                                        ("Z" . ignore))))


#+end_src

#+results:
: t


*** Auto Save and Revert

#+begin_src emacs-lisp
(run-at-time "00:59" 3600 'org-save-all-org-buffers)
(global-auto-revert-mode t)
#+end_src

#+results:
: t

*** org2blog
:LOGBOOK:
CLOCK: [2012-08-20 Mon 18:29]--[2012-08-20 Mon 18:29] =>  0:00
:END:
:PROPERTIES:
:OPEN: [2012-08-19 Sun 11:51]
:LAST:  [2012-09-09 Sun 12:30]
:CLOSE: [2012-09-09 Sun 12:30]
:END:

#+begin_src emacs-lisp
(require 'org2blog-autoloads)
#+end_src

#+results:
: org2blog-autoloads

#+begin_src emacs-lisp
  (setq org2blog/wp-blog-alist
       '(("scarce"
          :url "http://scarcecapital.com/wordpress/xmlrpc.php"
          :username "Tony Day")
         ("dev"
          :url "http://127.0.0.1:4001/wpdev/xmlrpc.php"
          :username "Tony Day"
          :default-title "test title (production)"
          :default-categories ("quant" "org" "emacs")
          :tags-as-categories nil)))
#+end_src

#+results:
| scarce | :url | http://scarcecapital.com/wordpress/xmlrpc.php | :username | Tony Day |                |                         |                     |                   |                     |     |
| dev    | :url | http://127.0.0.1:4001/wpdev/xmlrpc.php        | :username | Tony Day | :default-title | test title (production) | :default-categories | (quant org emacs) | :tags-as-categories | nil |





*** clipboard

#+begin_src emacs-lisp
  (setq org-cycle-global-at-bob t)
#+end_src

#+begin_src emacs-lisp :tangle no
(message "%s" "features")
(message "%s" features)
(message "%s" (locate-library "org-compat"))
  (load "org-compat")
  (require 'org-jsinfo)
#+end_src

#+results:
: org-compat

#+begin_src emacs-lisp :tangle no
  ; Enable habit tracking (and a bunch of other modules)
  (setq org-modules (quote (org-bbdb
                            org-bibtex
                            org-crypt
                            org-gnus
                            org-id
                            org-info
                            org-habit
                            org-inlinetask
                            org-irc
                            org-mew
                            org-mhe
                            org-protocol
                            org-rmail
                            org-vm
                            org-wl
                            org-w3m)))
  
  ; position the habit graph on the agenda to the right of the default
  (setq org-habit-graph-column 50)
  (require 'org-habit)
  
#+end_src

#+results:
: 50




#+begin_src emacs-lisp :tangle no
  (require 'org-jsinfo)

(require 'org-compat)

(library-path "org-compat")

(load "org-compat.elc")

  (locate-library "org-compat")

(load "org-compat")

#+end_src
*** MobileOrg hack

#+begin_src emacs-lisp
  (setq org-mobile-force-id-on-agenda-items nil)
  (setq org-directory "~")
(require 'org-habit)
#+end_src

*** org defuns
**** TODO Insert the last stored link
:PROPERTIES:
:OPEN: [2012-07-23 Mon 20:53]
:LAST: TODO [2012-07-23 Mon 20:53]
:ID:       56629caf-21e0-42c2-a6ac-69d78ff00993
:END:

- saving a button press
- [ ] broken
#+begin_src emacs-lisp
(defun org-insert-last-link()
  (interactive)
  (insert (concat "[[" 
        (plist-get org-store-link-plist :link)
        "]["
        (plist-get org-store-link-plist :description)
        "]]")))
#+end_src

#+results:
: org-insert-last-link


**** Get Timestamp as String
Return a timestamp string for use in my logging process.
#+begin_src emacs-lisp 
(defun org-string-timestamp (time &optional with-hm inactive pre post extra)
  "return a string for the date given by the internal TIME.
WITH-HM means use the stamp format that includes the time of the day.
INACTIVE means use square brackets instead of angular ones, so that the
stamp will not contribute to the agenda.
PRE and POST are optional strings to be inserted before and after the
stamp.
The command returns the time stamp as a string.
This is the same as org-insert-time-stamp without the insert.
"
  (let ((fmt (funcall (if with-hm 'cdr 'car) org-time-stamp-formats))
          stamp)
      (if inactive (setq fmt (concat "[" (substring fmt 1 -1) "]")))
      (when (listp extra)
        (setq extra (car extra))
        (if (and (stringp extra)
                 (string-match "\\([0-9]+\\):\\([0-9]+\\)" extra))
            (setq extra (format "-%02d:%02d"
                                (string-to-number (match-string 1 extra))
                                (string-to-number (match-string 2 extra))))
          (setq extra nil)))
      (when extra
        (setq fmt (concat (substring fmt 0 -1) extra (substring fmt -1))))
      (setq stamp (format-time-string fmt time))
      ))
#+end_src

#+results:
: org-string-timestamp

**** Log State Change
#+begin_src emacs-lisp 
  (defun zyg/log-state-change ()
    "logs timestamps in PROPERTIES for any todo-tag state change (LASTTOUCH),
      first state change (OPENED), and when last entered a done state
      (CLOSE).
  "
    (interactive)
    (save-excursion 
      (let* ((has-opened (org-entry-get nil "OPEN"))
             (stamp (org-string-timestamp nil t t nil nil nil)))
        (if (not has-opened)
            (org-set-property "OPEN" stamp))
        (if (or (equal org-state nil)
                (equal org-state "DONE"))
            (org-set-property "CLOSE" stamp))
        (if (or (equal org-state "TODO")
                (equal org-state "NEXT"))
            (org-entry-delete nil "CLOSE"))
        (org-set-property "LAST" (concatenate 'string org-state " " stamp)))))
#+end_src

#+results:
: zyg/log-state-change


**** =norang= general defuns
:PROPERTIES:
:OPEN: [2012-07-23 Mon 20:50]
:LAST:  [2012-08-01 Wed 13:54]
:CLOSE: [2012-08-01 Wed 13:54]
:END:


#+begin_src emacs-lisp 
(defun bh/show-org-agenda ()
    (interactive)
    (switch-to-buffer "*Org Agenda*")
    (delete-other-windows))

(defun bh/hide-other ()
  (interactive)
  (save-excursion
    (org-back-to-heading 'invisible-ok)
    (hide-other)
    (org-cycle)
    (org-cycle)
    (org-cycle)))

(defun bh/set-truncate-lines ()
  "Toggle value of truncate-lines and refresh window display."
  (interactive)
  (setq truncate-lines (not truncate-lines))
  ;; now refresh window display (an idiom from simple.el):
  (save-excursion
    (set-window-start (selected-window)
                      (window-start (selected-window)))))

(defun bh/org-todo (arg)
  (interactive "p")
  (if (equal arg 4)
      (save-restriction
        (widen)
        (org-narrow-to-subtree)
        (org-show-todo-tree nil))
    (widen)
    (org-narrow-to-subtree)
    (org-show-todo-tree nil)))

(defun bh/widen ()
  (interactive)
  (widen)
  (org-agenda-remove-restriction-lock))

(defun bh/restrict-to-file-or-follow (arg)
  "Set agenda restriction to 'file or with argument invoke follow mode.
I don't use follow mode very often but I restrict to file all the time
so change the default 'F' binding in the agenda to allow both"
  (interactive "p")
  (if (equal arg 4)
      (org-agenda-follow-mode)
    (if (equal major-mode 'org-agenda-mode)
        (bh/set-agenda-restriction-lock 4)
      (widen))))

(defun bh/narrow-to-org-subtree ()
  (widen)
  (org-narrow-to-subtree)
  (save-restriction
    (org-agenda-set-restriction-lock)))

(defun bh/narrow-to-subtree ()
  (interactive)
  (if (equal major-mode 'org-agenda-mode)
      (org-with-point-at (org-get-at-bol 'org-hd-marker)
        (bh/narrow-to-org-subtree))
    (bh/narrow-to-org-subtree)))

(defun bh/narrow-up-one-org-level ()
  (widen)
  (save-excursion
    (outline-up-heading 1 'invisible-ok)
    (bh/narrow-to-org-subtree)))

(defun bh/narrow-up-one-level ()
  (interactive)
  (if (equal major-mode 'org-agenda-mode)
      (org-with-point-at (org-get-at-bol 'org-hd-marker)
        (bh/narrow-up-one-org-level))
    (bh/narrow-up-one-org-level)))

(defun bh/narrow-to-org-project ()
  (widen)
  (save-excursion
    (bh/find-project-task)
    (bh/narrow-to-org-subtree)))

(defun bh/narrow-to-project ()
  (interactive)
  (if (equal major-mode 'org-agenda-mode)
      (org-with-point-at (org-get-at-bol 'org-hd-marker)
        (bh/narrow-to-org-project))
    (bh/narrow-to-org-project)))

(defun bh/set-agenda-restriction-lock (arg)
  "Set restriction lock to current task subtree or file if prefix is specified"
  (interactive "p")
  (let* ((pom (or (org-get-at-bol 'org-hd-marker)
                  org-agenda-restrict-begin))
         (tags (org-with-point-at pom (org-get-tags-at))))
    (let ((restriction-type (if (equal arg 4) 'file 'subtree)))
      (save-restriction
        (cond
         ((equal major-mode 'org-agenda-mode)
          (org-with-point-at pom
            (org-agenda-set-restriction-lock restriction-type)))
         ((and (equal major-mode 'org-mode) (org-before-first-heading-p))
          (org-agenda-set-restriction-lock 'file))
         (t
          (org-with-point-at pom
            (org-agenda-set-restriction-lock restriction-type))))))))

(defun bh/find-project-task ()
  "Move point to the parent (project) task if any"
  (save-restriction
    (widen)
    (let ((parent-task (save-excursion (org-back-to-heading 'invisible-ok) (point))))
      (while (org-up-heading-safe)
        (when (member (nth 2 (org-heading-components)) org-todo-keywords-1)
          (setq parent-task (point))))
      (goto-char parent-task)
      parent-task)))

(defun bh/show-org-agenda ()
    (interactive)
    (switch-to-buffer "*Org Agenda*")
    (delete-other-windows))




#+end_src

#+results:
: bh/show-org-agenda


**** =norang= agenda helper defuns

#+begin_src emacs-lisp 
    (defun bh/is-project-p ()
      "Any task with a todo keyword subtask"
      (save-restriction
        (widen)
        (let ((has-subtask)
              (subtree-end (save-excursion (org-end-of-subtree t)))
              (is-a-task (member (nth 2 (org-heading-components)) org-todo-keywords-1)))
          (save-excursion
            (forward-line 1)
            (while (and (not has-subtask)
                        (< (point) subtree-end)
                        (re-search-forward "^\*+ " subtree-end t))
              (when (member (org-get-todo-state) org-todo-keywords-1)
                (setq has-subtask t))))
          (and is-a-task has-subtask))))
    
    (defun bh/is-project-subtree-p ()
      "Any task with a todo keyword that is in a project subtree.
    Callers of this function already widen the buffer view."
      (let ((task (save-excursion (org-back-to-heading 'invisible-ok)
                                  (point))))
        (save-excursion
          (bh/find-project-task)
          (if (equal (point) task)
              nil
            t))))
    
    (defun bh/is-task-p ()
      "Any task with a todo keyword and no subtask"
      (save-restriction
        (widen)
        (let ((has-subtask)
              (subtree-end (save-excursion (org-end-of-subtree t)))
              (is-a-task (member (nth 2 (org-heading-components)) org-todo-keywords-1)))
          (save-excursion
            (forward-line 1)
            (while (and (not has-subtask)
                        (< (point) subtree-end)
                        (re-search-forward "^\*+ " subtree-end t))
              (when (member (org-get-todo-state) org-todo-keywords-1)
                (setq has-subtask t))))
          (and is-a-task (not has-subtask)))))
    
    (defun bh/is-subproject-p ()
      "Any task which is a subtask of another project"
      (let ((is-subproject)
            (is-a-task (member (nth 2 (org-heading-components)) org-todo-keywords-1)))
        (save-excursion
          (while (and (not is-subproject) (org-up-heading-safe))
            (when (member (nth 2 (org-heading-components)) org-todo-keywords-1)
              (setq is-subproject t))))
        (and is-a-task is-subproject)))
    
    (defun bh/list-sublevels-for-projects-indented ()
      "Set org-tags-match-list-sublevels so when restricted to a subtree we list all subtasks.
      This is normally used by skipping functions where this variable is already local to the agenda."
      (if (marker-buffer org-agenda-restrict-begin)
          (setq org-tags-match-list-sublevels 'indented)
        (setq org-tags-match-list-sublevels nil))
      nil)
    
    (defun bh/list-sublevels-for-projects ()
      "Set org-tags-match-list-sublevels so when restricted to a subtree we list all subtasks.
      This is normally used by skipping functions where this variable is already local to the agenda."
      (if (marker-buffer org-agenda-restrict-begin)
          (setq org-tags-match-list-sublevels t)
        (setq org-tags-match-list-sublevels nil))
      nil)
    
    (defun bh/skip-non-stuck-projects ()
      "Skip trees that are not stuck projects"
      (bh/list-sublevels-for-projects-indented)
      (save-restriction
        (widen)
        (let ((next-headline (save-excursion (or (outline-next-heading) (point-max)))))
          (if (bh/is-project-p)
              (let* ((subtree-end (save-excursion (org-end-of-subtree t)))
                     (has-next (save-excursion
                                 (forward-line 1)
                                 (and (< (point) subtree-end)
                                      (re-search-forward "^\\*+ \\(NEXT\\) " subtree-end t)))))
                (if has-next
                    next-headline
                  nil)) ; a stuck project, has subtasks but no next task
            next-headline))))
    
    (defun bh/skip-non-projects ()
      "Skip trees that are not projects"
      (bh/list-sublevels-for-projects-indented)
      (if (save-excursion (bh/skip-non-stuck-projects))
          (save-restriction
            (widen)
            (let ((subtree-end (save-excursion (org-end-of-subtree t))))
              (if (bh/is-project-p)
                  nil
                subtree-end)))
        (org-end-of-subtree t)))
    
    (defun bh/skip-project-trees-and-habits ()
      "Skip trees that are projects"
      (save-restriction
        (widen)
        (let ((subtree-end (save-excursion (org-end-of-subtree t))))
          (cond
           ((bh/is-project-p)
            subtree-end)
           ((org-is-habit-p)
            subtree-end)
           (t
            nil)))))
    
    (defun bh/skip-projects-and-habits-and-single-tasks ()
      "Skip trees that are projects, tasks that are habits, single non-project tasks"
      (save-restriction
        (widen)
        (let ((next-headline (save-excursion (or (outline-next-heading) (point-max)))))
          (cond
           ((org-is-habit-p)
            next-headline)
           ((bh/is-project-p)
            next-headline)
           ((and (bh/is-task-p) (not (bh/is-project-subtree-p)))
            next-headline)
           (t
            nil)))))
    
    (defun bh/skip-project-tasks-maybe ()
      "Show tasks related to the current restriction.
    When restricted to a project, skip project and sub project tasks, habits, NEXT tasks, and loose tasks.
    When not restricted, skip project and sub-project tasks, habits, and project related tasks."
      (save-restriction
        (widen)
        (let* ((subtree-end (save-excursion (org-end-of-subtree t)))
               (next-headline (save-excursion (or (outline-next-heading) (point-max))))
               (limit-to-project (marker-buffer org-agenda-restrict-begin)))
          (cond
           ((bh/is-project-p)
            next-headline)
           ((org-is-habit-p)
            subtree-end)
           ((and (not limit-to-project)
                 (bh/is-project-subtree-p))
            subtree-end)
           ((and limit-to-project
                 (bh/is-project-subtree-p)
                 (member (org-get-todo-state) (list "NEXT")))
            subtree-end)
           (t
            nil)))))
    
    (defun bh/skip-projects-and-habits ()
      "Skip trees that are projects and tasks that are habits"
      (save-restriction
        (widen)
        (let ((subtree-end (save-excursion (org-end-of-subtree t))))
          (cond
           ((bh/is-project-p)
            subtree-end)
           ((org-is-habit-p)
            subtree-end)
           (t
            nil)))))
    
    (defun bh/skip-non-subprojects ()
      "Skip trees that are not projects"
      (let ((next-headline (save-excursion (outline-next-heading))))
        (if (bh/is-subproject-p)
            nil
          next-headline)))
    
  (defun bh/skip-non-archivable-tasks ()
      "Skip trees that are not available for archiving"
      (save-restriction
        (widen)
        (let ((next-headline (save-excursion (or (outline-next-heading) (point-max)))))
          ;; Consider only tasks with done todo headings as archivable candidates
          (if (member (org-get-todo-state) org-done-keywords)
              (let* ((subtree-end (save-excursion (org-end-of-subtree t)))
                     (daynr (string-to-int (format-time-string "%d" (current-time))))
                     (a-month-ago (* 60 60 24 (+ daynr 1)))
                     (last-month (format-time-string "%Y-%m-" (time-subtract (current-time) (seconds-to-time a-month-ago))))
                     (this-month (format-time-string "%Y-%m-" (current-time)))
                     (subtree-is-current (save-excursion
                                           (forward-line 1)
                                           (and (< (point) subtree-end)
                                                (re-search-forward (concat last-month "\\|" this-month) subtree-end t)))))
                (if subtree-is-current
                    next-headline ; Has a date in this month or last month, skip it
                  nil))  ; available to archive
            (or next-headline (point-max))))))
  
#+end_src

#+results:
: bh/skip-non-archivable-tasks





**** =norang= agenda sort

#+begin_src emacs-lisp
  (defun bh/agenda-sort (a b)
    "Sorting strategy for agenda items.
  Late deadlines first, then scheduled, then non-late deadlines"
    (let (result num-a num-b)
      (cond
       ; time specific items are already sorted first by org-agenda-sorting-strategy
  
       ; non-deadline and non-scheduled items next
       ((bh/agenda-sort-test 'bh/is-not-scheduled-or-deadline a b))
  
       ; deadlines for today next
       ((bh/agenda-sort-test 'bh/is-due-deadline a b))
  
       ; late deadlines next
       ((bh/agenda-sort-test-num 'bh/is-late-deadline '< a b))
  
       ; scheduled items for today next
       ((bh/agenda-sort-test 'bh/is-scheduled-today a b))
  
       ; late scheduled items next
       ((bh/agenda-sort-test-num 'bh/is-scheduled-late '> a b))
  
       ; pending deadlines last
       ((bh/agenda-sort-test-num 'bh/is-pending-deadline '< a b))
  
       ; finally default to unsorted
       (t (setq result nil)))
      result))
  
  (defmacro bh/agenda-sort-test (fn a b)
    "Test for agenda sort"
    `(cond
      ; if both match leave them unsorted
      ((and (apply ,fn (list ,a))
            (apply ,fn (list ,b)))
       (setq result nil))
      ; if a matches put a first
      ((apply ,fn (list ,a))
       (setq result -1))
      ; otherwise if b matches put b first
      ((apply ,fn (list ,b))
       (setq result 1))
      ; if none match leave them unsorted
      (t nil)))
  
  (defmacro bh/agenda-sort-test-num (fn compfn a b)
    `(cond
      ((apply ,fn (list ,a))
       (setq num-a (string-to-number (match-string 1 ,a)))
       (if (apply ,fn (list ,b))
           (progn
             (setq num-b (string-to-number (match-string 1 ,b)))
             (setq result (if (apply ,compfn (list num-a num-b))
                              -1
                            1)))
         (setq result -1)))
      ((apply ,fn (list ,b))
       (setq result 1))
      (t nil)))
  
  (defun bh/is-not-scheduled-or-deadline (date-str)
    (and (not (bh/is-deadline date-str))
         (not (bh/is-scheduled date-str))))
  
  (defun bh/is-due-deadline (date-str)
    (string-match "Deadline:" date-str))
  
  (defun bh/is-late-deadline (date-str)
    (string-match "In *\\(-.*\\)d\.:" date-str))
  
  (defun bh/is-pending-deadline (date-str)
    (string-match "In \\([^-]*\\)d\.:" date-str))
  
  (defun bh/is-deadline (date-str)
    (or (bh/is-due-deadline date-str)
        (bh/is-late-deadline date-str)
        (bh/is-pending-deadline date-str)))
  
  (defun bh/is-scheduled (date-str)
    (or (bh/is-scheduled-today date-str)
        (bh/is-scheduled-late date-str)))
  
  (defun bh/is-scheduled-today (date-str)
    (string-match "Scheduled:" date-str))
  
  (defun bh/is-scheduled-late (date-str)
    (string-match "Sched\.\\(.*\\)x:" date-str))
#+end_src

#+results:
: bh/is-scheduled-late







** Octave
#+begin_src emacs-lisp 
  (autoload 'octave-mode "octave-mod" nil t)
  (setq auto-mode-alist
     (cons '("\\.m$" . octave-mode) auto-mode-alist))
  (add-hook 'octave-mode-hook
                      (lambda ()
                        (abbrev-mode 1)
                        (auto-fill-mode 1)
                        (if (eq window-system 'x)
                            (font-lock-mode 1))))

  ;; if you have the win32 version of octave
  (add-hook 'inferior-octave-mode-hook
             '(lambda ()
                 (setq inferior-octave-program
                     "octave")))
  
  ;; run an inferior Octave process in a special Emacs buffer
  (autoload 'run-octave "octave-inf" nil t)
#+end_src



* snippets
  :PROPERTIES:
  :tangle:   yes
  :END:
** dev code snippets
:PROPERTIES:
:OPEN: [2012-08-01 Wed 22:29]
:LAST: TODO [2012-08-01 Wed 22:29]
:ID: 50603d6b-021f-47bf-9a5e-22827e5932e8
:END:
- standard org bindings
  #+begin_src emacs-lisp
  (global-set-key "\C-ca" 'org-agenda)
  (global-set-key "\C-cc" 'org-capture)
  #+end_src

  #+results:
  : org-capture


- yegges binding suggestions
  #+begin_src emacs-lisp
  (global-set-key "\C-x\C-m" 'execute-extended-command)
  (global-set-key "\C-c\C-m" 'execute-extended-command)
  #+end_src

- backward kill word binding
  #+begin_src emacs-lisp
    (global-set-key "\C-w" 'backward-kill-word)
    (global-set-key "\C-x\C-k" 'kill-region)
    (global-set-key "\C-c\C-k" 'kill-region)
    (global-set-key [f4] 'call-last-kbd-macro)
  #+end_src

- saveplace
  #+begin_src emacs-lisp :tangle no 
    (setq-default save-place t)
  #+end_src

- transpose-windows
  #+begin_src emacs-lisp
    (defun transpose-windows (arg)
      "Transpose the buffers shown in two windows."
      (interactive "p")
      (let ((selector (if (>= arg 0) 'next-window 'previous-window)))
        (while (/= arg 0)
          (let ((this-win (window-buffer))
                (next-win (window-buffer (funcall selector))))
            (set-window-buffer (selected-window) next-win)
            (set-window-buffer (funcall selector) this-win)
            (select-window (funcall selector)))
          (setq arg (if (plusp arg) (1- arg) (1+ arg))))))
    (define-key ctl-x-4-map (kbd "t") 'transpose-windows)
  #+end_src

  #+results:
  : transpose-windows

- babel bindings
  #+begin_src emacs-lisp
    (global-set-key (kbd "<f11> s") 'org-babel-execute-subtree)
    (global-set-key (kbd "<f11> b") 'org-babel-execute-buffer)
    (global-set-key (kbd "<f11> t") 'org-table-recalculate-buffer-tables)
  #+end_src
- ido completion for yasnippet insertion
  #+begin_src emacs-lisp
    (setq yas/prompt-functions '(yas/ido-prompt yas/dropdown-prompt
                                                yas/completing-prompt yas/x-prompt yas/no-prompt))
  #+end_src

- yas/insert bound to f9-y
  #+begin_src emacs-lisp 
    (global-set-key (kbd "<f9> y") 'yas/insert-snippet)
  #+end_src

- kbd macro bindings
  #+begin_src emacs-lisp
    (global-set-key (kbd "<C-f4>") 'start-kbd-macro)
    (global-set-key (kbd "<S-f4>") 'end-kbd-macro)
  #+end_src

  #+results:
  : end-kbd-macro

- occur within isearch
  #+begin_src emacs-lisp
  ;; Activate occur easily inside isearch
  (define-key isearch-mode-map (kbd "C-o") 'isearch-occur)
  #+end_src




** nxhtml
:PROPERTIES:
:OPEN:     [2012-10-11 Thu 13:28]
:CLOSE:    [2012-10-11 Thu 13:28]
:LAST:     [2012-10-11 Thu 13:28]
:END:
  #+begin_src emacs-lisp 
    ;;(load (concat working-dir "src/nxhtml/autostart.el"))
  #+end_src


** magit info
  #+begin_src emacs-lisp :tangle no
    (add-to-list 'Info-default-directory-list "~/.emacs.d/git/magit")
  #+end_src

** simple bookmarks
:PROPERTIES:
:OPEN: [2012-07-23 Mon 10:49]
:LAST: TODO [2012-07-23 Mon 10:49]
:END:

#+begin_src emacs-lisp 
  (global-set-key (kbd "<C-f6>") 
                  '(lambda () (interactive) (bookmark-set "SAVED")))
  (global-set-key (kbd "<f6>")
                  '(lambda () (interactive) (bookmark-jump "SAVED")))
#+end_src

** buffer cycling

#+begin_src emacs-lisp 
  (global-set-key (kbd "C-<f9>") 'previous-buffer)
  (global-set-key (kbd "C-<f10>") 'next-buffer)
#+end_src

** tabify

#+begin_src emacs-lisp 
  (global-set-key (kbd "<f9> T") 'tabify)
  (global-set-key (kbd "<f9> U") 'untabify)
#+end_src

** Scratch
:PROPERTIES:
:OPEN: [2012-07-23 Mon 12:12]
:LAST:     [2012-10-11 Thu 13:28]
:CLOSE:    [2012-10-11 Thu 13:28]
:END:
All this scratching is making me itch.
- [ ] test these
- [ ] find out how/where *scratch*
- [ ] make a *escratch*
#+begin_src emacs-lisp 
  (global-set-key (kbd "<f9> o") 'make-org-scratch)
  (global-set-key (kbd "<f9> s") 'switch-to-org-scratch)
  (global-set-key (kbd "<f9> e") 'make-elisp-scratch)
  (global-set-key (kbd "<f9> z") 'switch-to-elisp-scratch)
#+end_src

Defuns
#+begin_src emacs-lisp 
(defun make-org-scratch ()
  (interactive)
  (find-file "~/.emacs.d/tmp/scratch.org")
  (ido-make-directory "~/.emacs.d/tmp"))  
(defun make-elisp-scratch ()
  (interactive)
  (find-file "~/.emacs.d/tmp/scratch.el")
  (ido-make-directory "~/.emacs.d/tmp"))  
(defun switch-to-org-scratch ()
  (interactive)
  (switch-to-buffer "*scratch*"))
(defun switch-to-elisp-scratch ()
  (interactive)
  (switch-to-buffer "*escratch*"))
#+end_src


** miscellaneous and overrides
:PROPERTIES:
:OPEN:     [2012-09-17 Mon 10:13]
:CLOSE:    [2012-09-17 Mon 10:13]
:LAST:     [2012-09-17 Mon 10:13]
:END:

#+begin_src emacs-lisp 
(setq shift-select-mode t)
(setq display-time-format " %I:%M%p %a %d %b ")
(display-time-mode)
(delete-selection-mode)
(setq ido-file-extensions-order '(".org"))
(setq sentence-end-double-space nil)  
#+end_src

#+results:

** A Column Number is always handy.
#+begin_src emacs-lisp
(column-number-mode t)
#+end_src


** register (off)

#+begin_example
 (?z (file . ,(concat working-dir "zygomega.org")))
#+end_example

** hunspell (off)
:PROPERTIES:
:OPEN: [2012-07-23 Mon 09:24]
:LAST:  [2012-08-03 Fri 15:21]
:CLOSE: [2012-08-03 Fri 15:21]
:tangle: no
:END:
Installing in windows involved a lot of tweaking, but hunspell is the
future.

*** Installing hunspell on Windows
It was a chore.  I had to:
- build hunspell from source (in Visual Studio 10)
- added a new directory (~/bin) to path to house it
- copied the hunspell.exe it over to ~/bin

http://sourceforge.net/projects/hunspell/

http://www.mail-archive.com/gnu-emacs-sources@gnu.org/msg01709.html

http://www.emacswiki.org/emacs/InteractiveSpell

personal dictionary is at ~/.personal_dicitionary

*** Packages and Settings

Why there are 3 packages, idk.
#+begin_src emacs-lisp
  (dolist (package '(rw-hunspell rw-ispell
                rw-language-and-country-codes))
    (unless (package-installed-p package)
      (package-install package)))
#+end_src

#+begin_src emacs-lisp 
  (require 'rw-hunspell)
  (require 'rw-ispell)
  (require 'rw-language-and-country-codes)
  (setq ispell-program-name "hunspell") 
  (setq ispell-dictionary "en_US_hunspell") ;the _suffix is the same as the name of the final dicpath directory
  ;; uses your home directory by default
  (setq ispell-process-directory (expand-file-name "~/.emacs.d/"))
  (setq rw-hunspell-dicpath-list '("~/hunspell")) ;spaces or special characters may be problematic
  (setq rw-hunspell-make-dictionary-menu t)
  (setq rw-hunspell-use-rw-ispell t)
  ;;(setq ispell-personal-dictionary (expand-file-name "~/.hunspell_en_US"))
#+end_src



** git folder list

#+begin_src emacs-lisp
      
        (setq magit-repo-dirs '("~/.emacs.d" 
                                "~/stuff"
                                "~/dotemacs-mashup"
                                "~/emfx"))
      
#+end_src

#+results:
| ~/.emacs.d | ~/stuff | ~/dotemacs-mashup | ~/emfx |




** sunrise commander

- M-x customize-group <RET> sunrise <RET> 
- M-x sunrise
- M-x sunrise-cd

#+begin_src emacs-lisp :tangle no
  (require 'sunrise-commander)
  (add-to-list 'auto-mode-alist '("\\.srvm\\'" . sr-virtual-mode))
#+end_src

** R
#+begin_src emacs-lisp
  (setq-default inferior-R-program-name "R")
  (require 'ess-site)
#+end_src
[[file:tonyday.org]]



** o-blog
#+begin_src emacs-lisp
  (require 'o-blog)
#+end_src



** plainlistify-paragraph
#+begin_src emacs-lisp
  (defun unfill-region (beg end)
      "Unfill the region, joining text paragraphs into a single
    logical line.  This is useful, e.g., for use with
    `visual-line-mode'."
      (interactive "*r")
      (let ((fill-column (point-max)))
        (fill-region beg end)))
    
    ;; Handy key definition
    (define-key global-map "\C-\M-Q" 'unfill-region)

  (defun unfill-paragraph ()
      "Takes a multi-line paragraph and makes it into a single line of text."
      (interactive)
      (let ((fill-column (point-max)))
        (fill-paragraph nil)))
    ;; Handy key definition
    (define-key global-map "\M-Q" 'unfill-paragraph)

#+end_src

#+results:
: unfill-paragraph





** org-clock
:PROPERTIES:
:OPEN: [2012-10-13 Sat 13:15]
:LAST: [2012-10-13 Sat 13:15]
:END:
#+begin_src emacs-lisp
  (require 'org-clock)
  (require 'org-colview)

#+end_src
** temporary key bindings
#+begin_src emacs-lisp
  (global-unset-key (kbd "<f10>"))
  (global-set-key (kbd "<f10> y") 'yas/new-snippet)
  (global-set-key (kbd "<f10> p") 'org-publish-blog)
  (global-set-key (kbd "<f10> d") 'scarce-to-dev)
  
#+end_src

#+results:
: scarce-to-dev


** ruby

#+begin_src emacs-lisp
  (setq exec-path (cons (expand-file-name "/usr/local/Cellar/ruby/1.9.3-p194/bin") exec-path))

#+end_src

#+results:
| /usr/local/Cellar/ruby/1.9.3-p194/bin | /Users/tonyday/.gem/ruby/1.8/bin | /usr/local/bin | /usr/local/sbin | /usr/bin | /bin | /usr/sbin | /sbin | /usr/texbin | /usr/local/Cellar/emacs/HEAD/libexec/emacs/24.2.50/i386-apple-darwin12.1.0 |


** ffip

#+begin_src emacs-lisp
  (require 'find-file-in-project)
#+end_src

#+results:
: find-file-in-project


** Info docs
:PROPERTIES:
:OPEN: [2012-08-01 Wed 14:05]
:LAST:  [2012-09-07 Fri 17:45]
:CLOSE: [2012-09-07 Fri 17:45]
:END:

There's various snafu's happening:

- Auctex seems to add to info-directory not default and this clobbers
  the default usage (cellar link). 
- ess adds elpa/doc/info (which doesnt exist)

So,
- using the table below
- change both info and default variables to the list
- first directory is my own with customised dir file there

#+TBLNAME: info-dirs
| /Users/tonyday/.emacs.d/info                   |
| /usr/share/info/                               |



| /usr/local/Cellar/emacs/HEAD/share/info/emacs/ |
| /Users/tonyday/.emacs.d/elpa/magit-1.1.1       |
| /Users/tonyday/.emacs.d/elpa/auctex-11.86      |



- function to reset org-agenda-files based on the above table of directories
  and files
  #+begin_src emacs-lisp :var table=info-dirs
     (setq clean-table
           (delete nil  
                   (loop for line in table
                         collect 
                         (delete "" (delete-dups line)))))
    (setq Info-default-directory-list (apply #'append clean-table))
    (setq Info-directory-list Info-default-directory-list)
  #+end_src

  #+results:
  | /Users/tonyday/.emacs.d/info | /usr/share/info/ |


#+begin_src emacs-lisp :tangle no
(add-to-list 'Info-default-directory-list "/Users/tonyday/.emacs.d/src/org-mode/doc/")
#+end_src

#+begin_src emacs-lisp :tangle no
  (add-to-list 'Info-directory-list "/Users/tonyday/.emacs.d/src/org-mode/doc/")
#+end_src

#+results:
| /Users/tonyday/.emacs.d/src/org-mode/doc/ | /Users/tonyday/.emacs.d/elpa/auctex-11.86 | /usr/share/info/ |


#+begin_src emacs-lisp :tangle no
  (getenv "INFOPATH")
#+end_src

#+begin_src emacs-lisp :tangle no
  (print (loop for f in Info-default-directory-list
               collect
               (list f)))
#+end_src

#+results:
| /Users/tonyday/.emacs.d/elpa/doc/info/         |
| /Users/tonyday/.emacs.d/src/org-mode/doc/      |
| /usr/local/Cellar/emacs/HEAD/share/info/emacs/ |
| /usr/share/info/                               |

#+begin_src emacs-lisp :tangle no
  (print (loop for f in Info-directory-list
               collect
               (car f)))
#+end_src

#+results:
| /Users/tonyday/.emacs.d/src/org-mode/doc/ |
| /Users/tonyday/.emacs.d/elpa/auctex-11.86 |
| /usr/share/info/                          |


** elnode
#+begin_src emacs-lisp
  ;;(require 'elnode)
#+end_src

* debug
:PROPERTIES:
:tangle:   no
:END:


** current message bugz

- prints out
  (table (quote (("stuff" "meta.org" "") (".emacs.d" "README.org" "") ("stuff" "org" "refile.org") ("stuff" "org" "bugz.org") ("stuff" "org" "snipz.org") ("stuff" "org" "org.org") ("stuff" "emacs" "emacs.org") ("stuff" "sys" "sys.org") ("stuff" "biz" "scarce.org") ("stuff" "site" "landing.org") ("stuff" "site" "scarcecapital.org") ("stuff" "content" "life.org") ("stuff" "content" "writing.org") ("stuff" "dev" "webdev.org") ("stuff" "emacs" "bindings.org") ("stuff" "sys" "git.org") ("stuff" "factor" "factor.org") ("stuff" "dev" "jsdev.org") ("stuff" "content" "ideas.org") ("git" "emfx_R" "emfx.org") ("git" "emfx_R" "volatility.org") ("git" "emfx_R" "rdev.org") ("git" "emfx_R" "xkcd.org") ("emfx" "README.org" ""))))

  (table (quote (("/Users/tonyday/.emacs.d/info") ("/usr/share/info/"))))

  at misc
  (yaml-mode clojure-mode ido paren anything-autoloads auctex-autoloads
  tex-site info cloj



#+begin_src emacs-lisp
  (print (loop for f in load-path
               collect
               (list f)))
#+end_src

#+RESULTS:
| src                                                                                        |
| /Users/tonyday/.emacs.d/elpa/ess-5.14/                                                     |
| /Users/tonyday/.emacs.d/src/yasnippet                                                      |
| /Users/tonyday/.emacs.d/elpa/anything-1.287                                                |
| /Users/tonyday/.emacs.d/elpa/auctex-11.86/                                                 |
| /Users/tonyday/.emacs.d/elpa/auctex-11.86                                                  |
| /Users/tonyday/.emacs.d/elpa/clojure-mode-1.11.5                                           |
| /Users/tonyday/.emacs.d/elpa/elisp-slime-nav-0.2                                           |
| /Users/tonyday/.emacs.d/elpa/ess-5.14                                                      |
| /Users/tonyday/.emacs.d/elpa/ess-smart-underscore-0.73                                     |
| /Users/tonyday/.emacs.d/elpa/find-file-in-project-3.2                                      |
| /Users/tonyday/.emacs.d/elpa/htmlize-1.39                                                  |
| /Users/tonyday/.emacs.d/elpa/js-comint-0.0.1                                               |
| /Users/tonyday/.emacs.d/elpa/js2-mode-20090814                                             |
| /Users/tonyday/.emacs.d/elpa/magithub-0.2                                                  |
| /Users/tonyday/.emacs.d/elpa/json-1.2                                                      |
| /Users/tonyday/.emacs.d/elpa/org-magit-0.2.0                                               |
| /Users/tonyday/.emacs.d/elpa/magit-1.1.1                                                   |
| /Users/tonyday/.emacs.d/elpa/org2blog-0.5                                                  |
| /Users/tonyday/.emacs.d/elpa/paredit-22                                                    |
| /Users/tonyday/.emacs.d/elpa/slime-20100404.1                                              |
| /Users/tonyday/.emacs.d/elpa/smex-1.1.4                                                    |
| /Users/tonyday/.emacs.d/elpa/xml-rpc-1.6.8                                                 |
| /Users/tonyday/.emacs.d/elpa/yaml-mode-0.0.7                                               |
| /Users/tonyday/.emacs.d/elpa/yasnippet-bundle-0.6.1                                        |
| /Users/tonyday/.emacs.d/elpa/zenburn-theme-1.5                                             |
| /Users/tonyday/.emacs.d/                                                                   |
| /Users/tonyday/.emacs.d/src                                                                |
| /Users/tonyday/.emacs.d/src/elnode                                                         |
| /Users/tonyday/.emacs.d/src/o-blog                                                         |
| /Users/tonyday/.emacs.d/src/org-ehtml                                                      |
| /Users/tonyday/.emacs.d/src/org-mac-protocol                                               |
| /Users/tonyday/.emacs.d/src/org-mode                                                       |
| /Users/tonyday/.emacs.d/src/org2blog                                                       |
| /Users/tonyday/.emacs.d/src/elnode/examples                                                |
| /Users/tonyday/.emacs.d/src/elnode/test_docroot                                            |
| /Users/tonyday/.emacs.d/src/o-blog/Font-Awesome                                            |
| /Users/tonyday/.emacs.d/src/o-blog/bootstrap                                               |
| /Users/tonyday/.emacs.d/src/o-blog/example                                                 |
| /Users/tonyday/.emacs.d/src/o-blog/less.js                                                 |
| /Users/tonyday/.emacs.d/src/o-blog/templates                                               |
| /Users/tonyday/.emacs.d/src/org-ehtml/src                                                  |
| /Users/tonyday/.emacs.d/src/org-ehtml/test                                                 |
| /Users/tonyday/.emacs.d/src/org-mac-protocol/orgQSLib                                      |
| /Users/tonyday/.emacs.d/src/org-mode/contrib                                               |
| /Users/tonyday/.emacs.d/src/org-mode/etc                                                   |
| /Users/tonyday/.emacs.d/src/org-mode/lisp                                                  |
| /Users/tonyday/.emacs.d/src/org-mode/mk                                                    |
| /Users/tonyday/.emacs.d/src/org-mode/testing                                               |
| /Users/tonyday/.emacs.d/src/o-blog/example/assets                                          |
| /Users/tonyday/.emacs.d/src/o-blog/example/out                                             |
| /Users/tonyday/.emacs.d/src/o-blog/templates/style                                         |
| /Users/tonyday/.emacs.d/src/org-ehtml/test/examples                                        |
| /Users/tonyday/.emacs.d/src/org-ehtml/test/lisp                                            |
| /Users/tonyday/.emacs.d/src/org-mode/contrib/babel                                         |
| /Users/tonyday/.emacs.d/src/org-mode/contrib/lisp                                          |
| /Users/tonyday/.emacs.d/src/org-mode/contrib/scripts                                       |
| /Users/tonyday/.emacs.d/src/org-mode/etc/schema                                            |
| /Users/tonyday/.emacs.d/src/org-mode/etc/styles                                            |
| /Users/tonyday/.emacs.d/src/org-mode/testing/examples                                      |
| /Users/tonyday/.emacs.d/src/org-mode/testing/jump                                          |
| /Users/tonyday/.emacs.d/src/org-mode/testing/lisp                                          |
| /Users/tonyday/.emacs.d/src/o-blog/example/out/assets                                      |
| /Users/tonyday/.emacs.d/src/o-blog/example/out/content                                     |
| /Users/tonyday/.emacs.d/src/o-blog/example/out/style                                       |
| /Users/tonyday/.emacs.d/src/o-blog/example/out/tags                                        |
| /Users/tonyday/.emacs.d/src/o-blog/example/out/tips                                        |
| /Users/tonyday/.emacs.d/src/o-blog/templates/style/Font-Awesome                            |
| /Users/tonyday/.emacs.d/src/o-blog/templates/style/bootstrap                               |
| /Users/tonyday/.emacs.d/src/o-blog/templates/style/font                                    |
| /Users/tonyday/.emacs.d/src/o-blog/templates/style/js                                      |
| /Users/tonyday/.emacs.d/src/o-blog/templates/style/less                                    |
| /Users/tonyday/.emacs.d/src/org-mode/contrib/babel/langs                                   |
| /Users/tonyday/.emacs.d/src/org-mode/contrib/scripts/staticmathjax                         |
| /Users/tonyday/.emacs.d/src/o-blog/example/out/content/2012                                |
| /Users/tonyday/.emacs.d/src/o-blog/example/out/style/Font-Awesome                          |
| /Users/tonyday/.emacs.d/src/o-blog/example/out/style/bootstrap                             |
| /Users/tonyday/.emacs.d/src/o-blog/example/out/style/font                                  |
| /Users/tonyday/.emacs.d/src/o-blog/example/out/style/js                                    |
| /Users/tonyday/.emacs.d/src/o-blog/example/out/style/less                                  |
| /Users/tonyday/.emacs.d/src/o-blog/example/out/tips/2012                                   |
| /Users/tonyday/.emacs.d/src/o-blog/templates/style/Font-Awesome/font                       |
| /Users/tonyday/.emacs.d/src/o-blog/templates/style/Font-Awesome/less                       |
| /Users/tonyday/.emacs.d/src/o-blog/templates/style/bootstrap/img                           |
| /Users/tonyday/.emacs.d/src/o-blog/templates/style/bootstrap/js                            |
| /Users/tonyday/.emacs.d/src/o-blog/templates/style/bootstrap/less                          |
| /Users/tonyday/.emacs.d/src/org-mode/contrib/scripts/staticmathjax/chrome                  |
| /Users/tonyday/.emacs.d/src/org-mode/contrib/scripts/staticmathjax/defaults                |
| /Users/tonyday/.emacs.d/src/o-blog/example/out/content/2012/10                             |
| /Users/tonyday/.emacs.d/src/o-blog/example/out/style/Font-Awesome/font                     |
| /Users/tonyday/.emacs.d/src/o-blog/example/out/style/Font-Awesome/less                     |
| /Users/tonyday/.emacs.d/src/o-blog/example/out/style/bootstrap/img                         |
| /Users/tonyday/.emacs.d/src/o-blog/example/out/style/bootstrap/js                          |
| /Users/tonyday/.emacs.d/src/o-blog/example/out/style/bootstrap/less                        |
| /Users/tonyday/.emacs.d/src/o-blog/example/out/tips/2012/01                                |
| /Users/tonyday/.emacs.d/src/o-blog/example/out/tips/2012/02                                |
| /Users/tonyday/.emacs.d/src/o-blog/example/out/tips/2012/05                                |
| /Users/tonyday/.emacs.d/src/o-blog/example/out/tips/2012/08                                |
| /Users/tonyday/.emacs.d/src/org-mode/contrib/scripts/staticmathjax/chrome/content          |
| /Users/tonyday/.emacs.d/src/org-mode/contrib/scripts/staticmathjax/defaults/preferences    |
| /Users/tonyday/.emacs.d/src/o-blog/example/out/tips/2012/01/07_example-of-some-org-syntax  |
| /Users/tonyday/.emacs.d/src/o-blog/example/out/tips/2012/08/21_adding-an-image-into-a-post |
| /Users/tonyday/.emacs.d/src/org-mode/lisp                                                  |
| /usr/local/share/emacs/site-lisp                                                           |
| /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp                                      |
| /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/vc                                   |
| /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/url                                  |
| /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/textmodes                            |
| /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/progmodes                            |
| /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/play                                 |
| /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/org                                  |
| /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/nxml                                 |
| /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/net                                  |
| /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/mh-e                                 |
| /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/mail                                 |
| /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/language                             |
| /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/international                        |
| /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/gnus                                 |
| /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/eshell                               |
| /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/erc                                  |
| /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/emulation                            |
| /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/emacs-lisp                           |
| /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/cedet                                |
| /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/calendar                             |
| /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/calc                                 |
| /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/obsolete                             |
| /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/leim                                      |



** test funct

#+begin_src emacs-lisp
  (defun test-funk ()
    (setq src-dir (expand-file-name "src" working-dir))
    ;; add the src directory to the load path
    (add-to-list 'load-path src-dir working-dir)
    ;; load all subdirectories
      (when (file-exists-p src-dir)
        (let ((default-directory src-dir))
          (normal-top-level-add-subdirs-to-load-path))))
#+end_src

#+results:
: test-funk

#+begin_src emacs-lisp
  (defun test-funk ()
    (setq src-dir (expand-file-name "src" working-dir))
     (when (file-exists-p src-dir)
        (add-to-list 'load-path src-dir)
        (mapc #'sk-load
              (remove-duplicates
               (mapcar #'remove-extension
                       (directory-files user-dir t ".*\.\\(org\\|el\\)\\(\\.gpg\\)?$"))
               :test #'string=))))))
#+end_src




#+results:
: test-funk

#+begin_src emacs-lisp
  (test-funk)
#+end_src

#+results:
| /Users/tonyday/.emacs.d/src/elnode | /Users/tonyday/.emacs.d/src/o-blog | /Users/tonyday/.emacs.d/src/org-ehtml | /Users/tonyday/.emacs.d/src/org-mac-protocol | /Users/tonyday/.emacs.d/src/org-mode | /Users/tonyday/.emacs.d/src/org2blog | /Users/tonyday/.emacs.d/src/elnode/examples | /Users/tonyday/.emacs.d/src/elnode/test_docroot | /Users/tonyday/.emacs.d/src/o-blog/Font-Awesome | /Users/tonyday/.emacs.d/src/o-blog/bootstrap | /Users/tonyday/.emacs.d/src/o-blog/example | /Users/tonyday/.emacs.d/src/o-blog/less.js | /Users/tonyday/.emacs.d/src/o-blog/templates | /Users/tonyday/.emacs.d/src/org-ehtml/src | /Users/tonyday/.emacs.d/src/org-ehtml/test | /Users/tonyday/.emacs.d/src/org-mac-protocol/orgQSLib | /Users/tonyday/.emacs.d/src/org-mode/contrib | /Users/tonyday/.emacs.d/src/org-mode/etc | /Users/tonyday/.emacs.d/src/org-mode/lisp | /Users/tonyday/.emacs.d/src/org-mode/mk | /Users/tonyday/.emacs.d/src/org-mode/testing | /Users/tonyday/.emacs.d/src/o-blog/example/assets | /Users/tonyday/.emacs.d/src/o-blog/example/out | /Users/tonyday/.emacs.d/src/o-blog/templates/style | /Users/tonyday/.emacs.d/src/org-ehtml/test/examples | /Users/tonyday/.emacs.d/src/org-ehtml/test/lisp | /Users/tonyday/.emacs.d/src/org-mode/contrib/babel | /Users/tonyday/.emacs.d/src/org-mode/contrib/lisp | /Users/tonyday/.emacs.d/src/org-mode/contrib/scripts | /Users/tonyday/.emacs.d/src/org-mode/etc/schema | /Users/tonyday/.emacs.d/src/org-mode/etc/styles | /Users/tonyday/.emacs.d/src/org-mode/testing/examples | /Users/tonyday/.emacs.d/src/org-mode/testing/jump | /Users/tonyday/.emacs.d/src/org-mode/testing/lisp | /Users/tonyday/.emacs.d/src/o-blog/example/out/assets | /Users/tonyday/.emacs.d/src/o-blog/example/out/content | /Users/tonyday/.emacs.d/src/o-blog/example/out/style | /Users/tonyday/.emacs.d/src/o-blog/example/out/tags | /Users/tonyday/.emacs.d/src/o-blog/example/out/tips | /Users/tonyday/.emacs.d/src/o-blog/templates/style/Font-Awesome | /Users/tonyday/.emacs.d/src/o-blog/templates/style/bootstrap | /Users/tonyday/.emacs.d/src/o-blog/templates/style/font | /Users/tonyday/.emacs.d/src/o-blog/templates/style/js | /Users/tonyday/.emacs.d/src/o-blog/templates/style/less | /Users/tonyday/.emacs.d/src/org-mode/contrib/babel/langs | /Users/tonyday/.emacs.d/src/org-mode/contrib/scripts/staticmathjax | /Users/tonyday/.emacs.d/src/o-blog/example/out/content/2012 | /Users/tonyday/.emacs.d/src/o-blog/example/out/style/Font-Awesome | /Users/tonyday/.emacs.d/src/o-blog/example/out/style/bootstrap | /Users/tonyday/.emacs.d/src/o-blog/example/out/style/font | /Users/tonyday/.emacs.d/src/o-blog/example/out/style/js | /Users/tonyday/.emacs.d/src/o-blog/example/out/style/less | /Users/tonyday/.emacs.d/src/o-blog/example/out/tips/2012 | /Users/tonyday/.emacs.d/src/o-blog/templates/style/Font-Awesome/font | /Users/tonyday/.emacs.d/src/o-blog/templates/style/Font-Awesome/less | /Users/tonyday/.emacs.d/src/o-blog/templates/style/bootstrap/img | /Users/tonyday/.emacs.d/src/o-blog/templates/style/bootstrap/js | /Users/tonyday/.emacs.d/src/o-blog/templates/style/bootstrap/less | /Users/tonyday/.emacs.d/src/org-mode/contrib/scripts/staticmathjax/chrome | /Users/tonyday/.emacs.d/src/org-mode/contrib/scripts/staticmathjax/defaults | /Users/tonyday/.emacs.d/src/o-blog/example/out/content/2012/10 | /Users/tonyday/.emacs.d/src/o-blog/example/out/style/Font-Awesome/font | /Users/tonyday/.emacs.d/src/o-blog/example/out/style/Font-Awesome/less | /Users/tonyday/.emacs.d/src/o-blog/example/out/style/bootstrap/img | /Users/tonyday/.emacs.d/src/o-blog/example/out/style/bootstrap/js | /Users/tonyday/.emacs.d/src/o-blog/example/out/style/bootstrap/less | /Users/tonyday/.emacs.d/src/o-blog/example/out/tips/2012/01 | /Users/tonyday/.emacs.d/src/o-blog/example/out/tips/2012/02 | /Users/tonyday/.emacs.d/src/o-blog/example/out/tips/2012/05 | /Users/tonyday/.emacs.d/src/o-blog/example/out/tips/2012/08 | /Users/tonyday/.emacs.d/src/org-mode/contrib/scripts/staticmathjax/chrome/content | /Users/tonyday/.emacs.d/src/org-mode/contrib/scripts/staticmathjax/defaults/preferences | /Users/tonyday/.emacs.d/src/o-blog/example/out/tips/2012/01/07_example-of-some-org-syntax | /Users/tonyday/.emacs.d/src/o-blog/example/out/tips/2012/08/21_adding-an-image-into-a-post | /Users/tonyday/.emacs.d/src/org-mode/lisp | /usr/local/share/emacs/site-lisp | /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp | /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/vc | /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/url | /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/textmodes | /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/progmodes | /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/play | /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/org | /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/nxml | /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/net | /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/mh-e | /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/mail | /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/language | /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/international | /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/gnus | /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/eshell | /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/erc | /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/emulation | /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/emacs-lisp | /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/cedet | /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/calendar | /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/calc | /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/lisp/obsolete | /usr/local/Cellar/emacs/HEAD/share/emacs/24.2.50/leim |


** test table quote etc

#+TBLNAME: test-table
| /Users/tonyday/.emacs.d/info                   |
| /usr/share/info/                               |


  #+begin_src emacs-lisp :var test-incoming-table=test-table
     (setq test-list
           (delete nil  
                   (loop for line in test-incoming-table
                         collect 
                         (delete "" (delete-dups line)))))
  #+end_src

  #+results:
  | /Users/tonyday/.emacs.d/info |
  | /usr/share/info/             |


#+begin_src emacs-lisp
  (load "t1test")
#+end_src

#+results:
: t



** test table with header

#+TBLNAME: table-with-header
| package   | essential |
|-----------+-----------|
| magit     | yes       |
| yasnippet | yes       |
|           |           |

  #+begin_src emacs-lisp :var test-incoming-table=table-with-header :results output
    (print test-incoming-table) 
 #+end_src

  #+results:
  : 
  : (("package" "essential") hline ("magit" "yes") ("yasnippet" "yes") ("" ""))



